package com.igor.listviewclick.EstadosCidades;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Igor on 18/03/2018.
 */

public class AL {

    List<String> cidades = new ArrayList<>();

    public AL() {}

    public List<String> getCidades() {

        this.cidades.add("Água Branca");
        this.cidades.add("Anadia");
        this.cidades.add("Arapiraca");
        this.cidades.add("Atalaia");
        this.cidades.add("Barra de Santo Antônio");
        this.cidades.add("Barra de São Miguel");
        this.cidades.add("Batalha");
        this.cidades.add("Belém");
        this.cidades.add("Belo Monte");
        this.cidades.add("Boca da Mata");
        this.cidades.add("Branquinha");
        this.cidades.add("Cacimbinhas");
        this.cidades.add("Cajueiro");
        this.cidades.add("Campestre");
        this.cidades.add("Campo Alegre");
        this.cidades.add("Campo Grande");
        this.cidades.add("Canapi");
        this.cidades.add("Capela");
        this.cidades.add("Carneiros");
        this.cidades.add("Chã Preta");
        this.cidades.add("Coité do Nóia");
        this.cidades.add("Colônia Leopoldina");
        this.cidades.add("Coqueiro Seco");
        this.cidades.add("Coruripe");
        this.cidades.add("Craíbas");
        this.cidades.add("Delmiro Gouveia");
        this.cidades.add("Dois Riachos");
        this.cidades.add("Estrela de Alagoas");
        this.cidades.add("Feira Grande");
        this.cidades.add("Feliz Deserto");
        this.cidades.add("Flexeiras");
        this.cidades.add("Girau do Ponciano");
        this.cidades.add("Ibateguara");
        this.cidades.add("Igaci");
        this.cidades.add("Igreja Nova");
        this.cidades.add("Inhapi");
        this.cidades.add("Jacaré dos Homens");
        this.cidades.add("Jacuípe");
        this.cidades.add("Japaratinga");
        this.cidades.add("Jaramataia");
        this.cidades.add("Jequiá da Praia");
        this.cidades.add("Joaquim Gomes");
        this.cidades.add("Jundiá");
        this.cidades.add("Junqueiro");
        this.cidades.add("Lagoa da Canoa");
        this.cidades.add("Limoeiro de Anadia");
        this.cidades.add("Maceió");
        this.cidades.add("Major Isidoro");
        this.cidades.add("Maragogi");
        this.cidades.add("Maravilha");
        this.cidades.add("Marechal Deodoro");
        this.cidades.add("Maribondo");
        this.cidades.add("Mar Vermelho");
        this.cidades.add("Mata Grande");
        this.cidades.add("Matriz de Camaragibe");
        this.cidades.add("Messias");
        this.cidades.add("Minador do Negrão");
        this.cidades.add("Monteirópolis");
        this.cidades.add("Murici");
        this.cidades.add("Novo Lino");
        this.cidades.add("Olho D'Água das Flores");
        this.cidades.add("Olho D'Água do Casado");
        this.cidades.add("Olho D'Água Grande");
        this.cidades.add("Olivença");
        this.cidades.add("Ouro Branco");
        this.cidades.add("Palestina");
        this.cidades.add("Palmeira dos Índios");
        this.cidades.add("Pão de Açúcar");
        this.cidades.add("Pariconha");
        this.cidades.add("Paripueira");
        this.cidades.add("Passo de Camaragibe");
        this.cidades.add("Paulo Jacinto");
        this.cidades.add("Penedo");
        this.cidades.add("Piaçabuçu");
        this.cidades.add("Pilar");
        this.cidades.add("Pindoba");
        this.cidades.add("Piranhas");
        this.cidades.add("Poço das Trincheiras");
        this.cidades.add("Porto Calvo");
        this.cidades.add("Porto de Pedras");
        this.cidades.add("Porto Real do Colégio");
        this.cidades.add("Quebrangulo");
        this.cidades.add("Rio Largo");
        this.cidades.add("Roteiro");
        this.cidades.add("Santa Luzia do Norte");
        this.cidades.add("Santana do Ipanema");
        this.cidades.add("Santana do Mundaú");
        this.cidades.add("São Brás");
        this.cidades.add("São José da Laje");
        this.cidades.add("São José da Tapera");
        this.cidades.add("São Luís do Quitunde");
        this.cidades.add("São Miguel dos Campos");
        this.cidades.add("São Miguel dos Milagres");
        this.cidades.add("São Sebastião");
        this.cidades.add("Satuba");
        this.cidades.add("Senador Rui Palmeira");
        this.cidades.add("Tanque D'Arca");
        this.cidades.add("Taquarana");
        this.cidades.add("Teotônio Vilela");
        this.cidades.add("Traipu");
        this.cidades.add("União dos Palmares");
        this.cidades.add("Viçosa");
        this.cidades.add("Água Branca");
        this.cidades.add("Anadia");
        this.cidades.add("Arapiraca");
        this.cidades.add("Atalaia");
        this.cidades.add("Barra de Santo Antônio");
        this.cidades.add("Barra de São Miguel");
        this.cidades.add("Batalha");
        this.cidades.add("Belém");
        this.cidades.add("Belo Monte");
        this.cidades.add("Boca da Mata");
        this.cidades.add("Branquinha");
        this.cidades.add("Cacimbinhas");
        this.cidades.add("Cajueiro");
        this.cidades.add("Campestre");
        this.cidades.add("Campo Alegre");
        this.cidades.add("Campo Grande");
        this.cidades.add("Canapi");
        this.cidades.add("Capela");
        this.cidades.add("Carneiros");
        this.cidades.add("Chã Preta");
        this.cidades.add("Coité do Nóia");
        this.cidades.add("Colônia Leopoldina");
        this.cidades.add("Coqueiro Seco");
        this.cidades.add("Coruripe");
        this.cidades.add("Craíbas");
        this.cidades.add("Delmiro Gouveia");
        this.cidades.add("Dois Riachos");
        this.cidades.add("Estrela de Alagoas");
        this.cidades.add("Feira Grande");
        this.cidades.add("Feliz Deserto");
        this.cidades.add("Flexeiras");
        this.cidades.add("Girau do Ponciano");
        this.cidades.add("Ibateguara");
        this.cidades.add("Igaci");
        this.cidades.add("Igreja Nova");
        this.cidades.add("Inhapi");
        this.cidades.add("Jacaré dos Homens");
        this.cidades.add("Jacuípe");
        this.cidades.add("Japaratinga");
        this.cidades.add("Jaramataia");
        this.cidades.add("Jequiá da Praia");
        this.cidades.add("Joaquim Gomes");
        this.cidades.add("Jundiá");
        this.cidades.add("Junqueiro");
        this.cidades.add("Lagoa da Canoa");
        this.cidades.add("Limoeiro de Anadia");
        this.cidades.add("Maceió");
        this.cidades.add("Major Isidoro");
        this.cidades.add("Maragogi");
        this.cidades.add("Maravilha");
        this.cidades.add("Marechal Deodoro");
        this.cidades.add("Maribondo");
        this.cidades.add("Mar Vermelho");
        this.cidades.add("Mata Grande");
        this.cidades.add("Matriz de Camaragibe");
        this.cidades.add("Messias");
        this.cidades.add("Minador do Negrão");
        this.cidades.add("Monteirópolis");
        this.cidades.add("Murici");
        this.cidades.add("Novo Lino");
        this.cidades.add("Olho D'Água das Flores");
        this.cidades.add("Olho D'Água do Casado");
        this.cidades.add("Olho D'Água Grande");
        this.cidades.add("Olivença");
        this.cidades.add("Ouro Branco");
        this.cidades.add("Palestina");
        this.cidades.add("Palmeira dos Índios");
        this.cidades.add("Pão de Açúcar");
        this.cidades.add("Pariconha");
        this.cidades.add("Paripueira");
        this.cidades.add("Passo de Camaragibe");
        this.cidades.add("Paulo Jacinto");
        this.cidades.add("Penedo");
        this.cidades.add("Piaçabuçu");
        this.cidades.add("Pilar");
        this.cidades.add("Pindoba");
        this.cidades.add("Piranhas");
        this.cidades.add("Poço das Trincheiras");
        this.cidades.add("Porto Calvo");
        this.cidades.add("Porto de Pedras");
        this.cidades.add("Porto Real do Colégio");
        this.cidades.add("Quebrangulo");
        this.cidades.add("Rio Largo");
        this.cidades.add("Roteiro");
        this.cidades.add("Santa Luzia do Norte");
        this.cidades.add("Santana do Ipanema");
        this.cidades.add("Santana do Mundaú");
        this.cidades.add("São Brás");
        this.cidades.add("São José da Laje");
        this.cidades.add("São José da Tapera");
        this.cidades.add("São Luís do Quitunde");
        this.cidades.add("São Miguel dos Campos");
        this.cidades.add("São Miguel dos Milagres");
        this.cidades.add("São Sebastião");
        this.cidades.add("Satuba");
        this.cidades.add("Senador Rui Palmeira");
        this.cidades.add("Tanque D'Arca");
        this.cidades.add("Taquarana");
        this.cidades.add("Teotônio Vilela");
        this.cidades.add("Traipu");
        this.cidades.add("União dos Palmares");
        this.cidades.add("Viçosa");

        return cidades;
    }
}
