package com.igor.listviewclick.EstadosCidades;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Igor on 18/03/2018.
 */

public class BA {

    List<String> cidades = new ArrayList<>();

    public BA() {}

    public List<String> getCidades() {

        this.cidades.add("Abaíra");
        this.cidades.add("Abaré");
        this.cidades.add("Acajutiba");
        this.cidades.add("Adustina");
        this.cidades.add("Água Fria");
        this.cidades.add("Érico Cardoso");
        this.cidades.add("Aiquara");
        this.cidades.add("Alagoinhas");
        this.cidades.add("Alcobaça");
        this.cidades.add("Almadina");
        this.cidades.add("Amargosa");
        this.cidades.add("Amélia Rodrigues");
        this.cidades.add("América Dourada");
        this.cidades.add("Anagé");
        this.cidades.add("Andaraí");
        this.cidades.add("Andorinha");
        this.cidades.add("Angical");
        this.cidades.add("Anguera");
        this.cidades.add("Antas");
        this.cidades.add("Antônio Cardoso");
        this.cidades.add("Antônio Gonçalves");
        this.cidades.add("Aporá");
        this.cidades.add("Apuarema");
        this.cidades.add("Aracatu");
        this.cidades.add("Araças");
        this.cidades.add("Araci");
        this.cidades.add("Aramari");
        this.cidades.add("Arataca");
        this.cidades.add("Aratuípe");
        this.cidades.add("Aurelino Leal");
        this.cidades.add("Baianópolis");
        this.cidades.add("Baixa Grande");
        this.cidades.add("Banzaê");
        this.cidades.add("Barra");
        this.cidades.add("Barra da Estiva");
        this.cidades.add("Barra do Choça");
        this.cidades.add("Barra do Mendes");
        this.cidades.add("Barra do Rocha");
        this.cidades.add("Barreiras");
        this.cidades.add("Barro Alto");
        this.cidades.add("Barrocas");
        this.cidades.add("Barro Preto");
        this.cidades.add("Belmonte");
        this.cidades.add("Belo Campo");
        this.cidades.add("Biritinga");
        this.cidades.add("Boa Nova");
        this.cidades.add("Boa Vista do Tupim");
        this.cidades.add("Bom Jesus da Lapa");
        this.cidades.add("Bom Jesus da Serra");
        this.cidades.add("Boninal");
        this.cidades.add("Bonito");
        this.cidades.add("Boquira");
        this.cidades.add("Botuporã");
        this.cidades.add("Brejões");
        this.cidades.add("Brejolândia");
        this.cidades.add("Brotas de Macaúbas");
        this.cidades.add("Brumado");
        this.cidades.add("Buerarema");
        this.cidades.add("Buritirama");
        this.cidades.add("Caatiba");
        this.cidades.add("Cabaceiras do Paraguaçu");
        this.cidades.add("Cachoeira");
        this.cidades.add("Caculé");
        this.cidades.add("Caém");
        this.cidades.add("Caetanos");
        this.cidades.add("Caetité");
        this.cidades.add("Cafarnaum");
        this.cidades.add("Cairu");
        this.cidades.add("Caldeirão Grande");
        this.cidades.add("Camacan");
        this.cidades.add("Camaçari");
        this.cidades.add("Camamu");
        this.cidades.add("Campo Alegre de Lourdes");
        this.cidades.add("Campo Formoso");
        this.cidades.add("Canápolis");
        this.cidades.add("Canarana");
        this.cidades.add("Canavieiras");
        this.cidades.add("Candeal");
        this.cidades.add("Candeias");
        this.cidades.add("Candiba");
        this.cidades.add("Cândido Sales");
        this.cidades.add("Cansanção");
        this.cidades.add("Canudos");
        this.cidades.add("Capela do Alto Alegre");
        this.cidades.add("Capim Grosso");
        this.cidades.add("Caraíbas");
        this.cidades.add("Caravelas");
        this.cidades.add("Cardeal da Silva");
        this.cidades.add("Carinhanha");
        this.cidades.add("Casa Nova");
        this.cidades.add("Castro Alves");
        this.cidades.add("Catolândia");
        this.cidades.add("Catu");
        this.cidades.add("Caturama");
        this.cidades.add("Central");
        this.cidades.add("Chorrochó");
        this.cidades.add("Cícero Dantas");
        this.cidades.add("Cipó");
        this.cidades.add("Coaraci");
        this.cidades.add("Cocos");
        this.cidades.add("Conceição da Feira");
        this.cidades.add("Conceição do Almeida");
        this.cidades.add("Conceição do Coité");
        this.cidades.add("Conceição do Jacuípe");
        this.cidades.add("Conde");
        this.cidades.add("Condeúba");
        this.cidades.add("Contendas do Sincorá");
        this.cidades.add("Coração de Maria");
        this.cidades.add("Cordeiros");
        this.cidades.add("Coribe");
        this.cidades.add("Coronel João Sá");
        this.cidades.add("Correntina");
        this.cidades.add("Cotegipe");
        this.cidades.add("Cravolândia");
        this.cidades.add("Crisópolis");
        this.cidades.add("Cristópolis");
        this.cidades.add("Cruz das Almas");
        this.cidades.add("Curaçá");
        this.cidades.add("Dário Meira");
        this.cidades.add("Dias D'Ávila");
        this.cidades.add("Dom Basílio");
        this.cidades.add("Dom Macedo Costa");
        this.cidades.add("Elísio Medrado");
        this.cidades.add("Encruzilhada");
        this.cidades.add("Entre Rios");
        this.cidades.add("Esplanada");
        this.cidades.add("Euclides da Cunha");
        this.cidades.add("Eunápolis");
        this.cidades.add("Fátima");
        this.cidades.add("Feira da Mata");
        this.cidades.add("Feira de Santana");
        this.cidades.add("Filadélfia");
        this.cidades.add("Firmino Alves");
        this.cidades.add("Floresta Azul");
        this.cidades.add("Formosa do Rio Preto");
        this.cidades.add("Gandu");
        this.cidades.add("Gavião");
        this.cidades.add("Gentio do Ouro");
        this.cidades.add("Glória");
        this.cidades.add("Gongogi");
        this.cidades.add("Governador Mangabeira");
        this.cidades.add("Guajeru");
        this.cidades.add("Guanambi");
        this.cidades.add("Guaratinga");
        this.cidades.add("Heliópolis");
        this.cidades.add("Iaçu");
        this.cidades.add("Ibiassucê");
        this.cidades.add("Ibicaraí");
        this.cidades.add("Ibicoara");
        this.cidades.add("Ibicuí");
        this.cidades.add("Ibipeba");
        this.cidades.add("Ibipitanga");
        this.cidades.add("Ibiquera");
        this.cidades.add("Ibirapitanga");
        this.cidades.add("Ibirapuã");
        this.cidades.add("Ibirataia");
        this.cidades.add("Ibitiara");
        this.cidades.add("Ibititá");
        this.cidades.add("Ibotirama");
        this.cidades.add("Ichu");
        this.cidades.add("Igaporã");
        this.cidades.add("Igrapiúna");
        this.cidades.add("Iguaí");
        this.cidades.add("Ilhéus");
        this.cidades.add("Inhambupe");
        this.cidades.add("Ipecaetá");
        this.cidades.add("Ipiaú");
        this.cidades.add("Ipirá");
        this.cidades.add("Ipupiara");
        this.cidades.add("Irajuba");
        this.cidades.add("Iramaia");
        this.cidades.add("Iraquara");
        this.cidades.add("Irará");
        this.cidades.add("Irecê");
        this.cidades.add("Itabela");
        this.cidades.add("Itaberaba");
        this.cidades.add("Itabuna");
        this.cidades.add("Itacaré");
        this.cidades.add("Itaeté");
        this.cidades.add("Itagi");
        this.cidades.add("Itagibá");
        this.cidades.add("Itagimirim");
        this.cidades.add("Itaguaçu da Bahia");
        this.cidades.add("Itaju do Colônia");
        this.cidades.add("Itajuípe");
        this.cidades.add("Itamaraju");
        this.cidades.add("Itamari");
        this.cidades.add("Itambé");
        this.cidades.add("Itanagra");
        this.cidades.add("Itanhém");
        this.cidades.add("Itaparica");
        this.cidades.add("Itapé");
        this.cidades.add("Itapebi");
        this.cidades.add("Itapetinga");
        this.cidades.add("Itapicuru");
        this.cidades.add("Itapitanga");
        this.cidades.add("Itaquara");
        this.cidades.add("Itarantim");
        this.cidades.add("Itatim");
        this.cidades.add("Itiruçu");
        this.cidades.add("Itiúba");
        this.cidades.add("Itororó");
        this.cidades.add("Ituaçu");
        this.cidades.add("Ituberá");
        this.cidades.add("Iuiú");
        this.cidades.add("Jaborandi");
        this.cidades.add("Jacaraci");
        this.cidades.add("Jacobina");
        this.cidades.add("Jaguaquara");
        this.cidades.add("Jaguarari");
        this.cidades.add("Jaguaripe");
        this.cidades.add("Jandaíra");
        this.cidades.add("Jequié");
        this.cidades.add("Jeremoabo");
        this.cidades.add("Jiquiriçá");
        this.cidades.add("Jitaúna");
        this.cidades.add("João Dourado");
        this.cidades.add("Juazeiro");
        this.cidades.add("Jucuruçu");
        this.cidades.add("Jussara");
        this.cidades.add("Jussari");
        this.cidades.add("Jussiape");
        this.cidades.add("Lafaiete Coutinho");
        this.cidades.add("Lagoa Real");
        this.cidades.add("Laje");
        this.cidades.add("Lajedão");
        this.cidades.add("Lajedinho");
        this.cidades.add("Lajedo do Tabocal");
        this.cidades.add("Lamarão");
        this.cidades.add("Lapão");
        this.cidades.add("Lauro de Freitas");
        this.cidades.add("Lençóis");
        this.cidades.add("Licínio de Almeida");
        this.cidades.add("Livramento de Nossa Senhora");
        this.cidades.add("Luís Eduardo Magalhães");
        this.cidades.add("Macajuba");
        this.cidades.add("Macarani");
        this.cidades.add("Macaúbas");
        this.cidades.add("Macururé");
        this.cidades.add("Madre de Deus");
        this.cidades.add("Maetinga");
        this.cidades.add("Maiquinique");
        this.cidades.add("Mairi");
        this.cidades.add("Malhada");
        this.cidades.add("Malhada de Pedras");
        this.cidades.add("Manoel Vitorino");
        this.cidades.add("Mansidão");
        this.cidades.add("Maracás");
        this.cidades.add("Maragogipe");
        this.cidades.add("Maraú");
        this.cidades.add("Marcionílio Souza");
        this.cidades.add("Mascote");
        this.cidades.add("Mata de São João");
        this.cidades.add("Matina");
        this.cidades.add("Medeiros Neto");
        this.cidades.add("Miguel Calmon");
        this.cidades.add("Milagres");
        this.cidades.add("Mirangaba");
        this.cidades.add("Mirante");
        this.cidades.add("Monte Santo");
        this.cidades.add("Morpará");
        this.cidades.add("Morro do Chapéu");
        this.cidades.add("Mortugaba");
        this.cidades.add("Mucugê");
        this.cidades.add("Mucuri");
        this.cidades.add("Mulungu do Morro");
        this.cidades.add("Mundo Novo");
        this.cidades.add("Muniz Ferreira");
        this.cidades.add("Muquém de São Francisco");
        this.cidades.add("Muritiba");
        this.cidades.add("Mutuípe");
        this.cidades.add("Nazaré");
        this.cidades.add("Nilo Peçanha");
        this.cidades.add("Nordestina");
        this.cidades.add("Nova Canaã");
        this.cidades.add("Nova Fátima");
        this.cidades.add("Nova Ibiá");
        this.cidades.add("Nova Itarana");
        this.cidades.add("Nova Redenção");
        this.cidades.add("Nova Soure");
        this.cidades.add("Nova Viçosa");
        this.cidades.add("Novo Horizonte");
        this.cidades.add("Novo Triunfo");
        this.cidades.add("Olindina");
        this.cidades.add("Oliveira dos Brejinhos");
        this.cidades.add("Ouriçangas");
        this.cidades.add("Ourolândia");
        this.cidades.add("Palmas de Monte Alto");
        this.cidades.add("Palmeiras");
        this.cidades.add("Paramirim");
        this.cidades.add("Paratinga");
        this.cidades.add("Paripiranga");
        this.cidades.add("Pau Brasil");
        this.cidades.add("Paulo Afonso");
        this.cidades.add("Pé de Serra");
        this.cidades.add("Pedrão");
        this.cidades.add("Pedro Alexandre");
        this.cidades.add("Piatã");
        this.cidades.add("Pilão Arcado");
        this.cidades.add("Pindaí");
        this.cidades.add("Pindobaçu");
        this.cidades.add("Pintadas");
        this.cidades.add("Piraí do Norte");
        this.cidades.add("Piripá");
        this.cidades.add("Piritiba");
        this.cidades.add("Planaltino");
        this.cidades.add("Planalto");
        this.cidades.add("Poções");
        this.cidades.add("Pojuca");
        this.cidades.add("Ponto Novo");
        this.cidades.add("Porto Seguro");
        this.cidades.add("Potiraguá");
        this.cidades.add("Prado");
        this.cidades.add("Presidente Dutra");
        this.cidades.add("Presidente Jânio Quadros");
        this.cidades.add("Presidente Tancredo Neves");
        this.cidades.add("Queimadas");
        this.cidades.add("Quijingue");
        this.cidades.add("Quixabeira");
        this.cidades.add("Rafael Jambeiro");
        this.cidades.add("Remanso");
        this.cidades.add("Retirolândia");
        this.cidades.add("Riachão das Neves");
        this.cidades.add("Riachão do Jacuípe");
        this.cidades.add("Riacho de Santana");
        this.cidades.add("Ribeira do Amparo");
        this.cidades.add("Ribeira do Pombal");
        this.cidades.add("Ribeirão do Largo");
        this.cidades.add("Rio de Contas");
        this.cidades.add("Rio do Antônio");
        this.cidades.add("Rio do Pires");
        this.cidades.add("Rio Real");
        this.cidades.add("Rodelas");
        this.cidades.add("Ruy Barbosa");
        this.cidades.add("Salinas da Margarida");
        this.cidades.add("Salvador");
        this.cidades.add("Santa Bárbara");
        this.cidades.add("Santa Brígida");
        this.cidades.add("Santa Cruz Cabrália");
        this.cidades.add("Santa Cruz da Vitória");
        this.cidades.add("Santa Inês");
        this.cidades.add("Santaluz");
        this.cidades.add("Santa Luzia");
        this.cidades.add("Santa Maria da Vitória");
        this.cidades.add("Santana");
        this.cidades.add("Santanópolis");
        this.cidades.add("Santa Rita de Cássia");
        this.cidades.add("Santa Teresinha");
        this.cidades.add("Santo Amaro");
        this.cidades.add("Santo Antônio de Jesus");
        this.cidades.add("Santo Estêvão");
        this.cidades.add("São Desidério");
        this.cidades.add("São Domingos");
        this.cidades.add("São Félix");
        this.cidades.add("São Félix do Coribe");
        this.cidades.add("São Felipe");
        this.cidades.add("São Francisco do Conde");
        this.cidades.add("São Gabriel");
        this.cidades.add("São Gonçalo dos Campos");
        this.cidades.add("São José da Vitória");
        this.cidades.add("São José do Jacuípe");
        this.cidades.add("São Miguel das Matas");
        this.cidades.add("São Sebastião do Passé");
        this.cidades.add("Sapeaçu");
        this.cidades.add("Sátiro Dias");
        this.cidades.add("Saubara");
        this.cidades.add("Saúde");
        this.cidades.add("Seabra");
        this.cidades.add("Sebastião Laranjeiras");
        this.cidades.add("Senhor do Bonfim");
        this.cidades.add("Serra do Ramalho");
        this.cidades.add("Sento Sé");
        this.cidades.add("Serra Dourada");
        this.cidades.add("Serra Preta");
        this.cidades.add("Serrinha");
        this.cidades.add("Serrolândia");
        this.cidades.add("Simões Filho");
        this.cidades.add("Sítio do Mato");
        this.cidades.add("Sítio do Quinto");
        this.cidades.add("Sobradinho");
        this.cidades.add("Souto Soares");
        this.cidades.add("Tabocas do Brejo Velho");
        this.cidades.add("Tanhaçu");
        this.cidades.add("Tanque Novo");
        this.cidades.add("Tanquinho");
        this.cidades.add("Taperoá");
        this.cidades.add("Tapiramutá");
        this.cidades.add("Teixeira de Freitas");
        this.cidades.add("Teodoro Sampaio");
        this.cidades.add("Teofilândia");
        this.cidades.add("Teolândia");
        this.cidades.add("Terra Nova");
        this.cidades.add("Tremedal");
        this.cidades.add("Tucano");
        this.cidades.add("Uauá");
        this.cidades.add("Ubaíra");
        this.cidades.add("Ubaitaba");
        this.cidades.add("Ubatã");
        this.cidades.add("Uibaí");
        this.cidades.add("Umburanas");
        this.cidades.add("Una");
        this.cidades.add("Urandi");
        this.cidades.add("Uruçuca");
        this.cidades.add("Utinga");
        this.cidades.add("Valença");
        this.cidades.add("Valente");
        this.cidades.add("Várzea da Roça");
        this.cidades.add("Várzea do Poço");
        this.cidades.add("Várzea Nova");
        this.cidades.add("Varzedo");
        this.cidades.add("Vera Cruz");
        this.cidades.add("Vereda");
        this.cidades.add("Vitória da Conquista");
        this.cidades.add("Wagner");
        this.cidades.add("Wanderley");
        this.cidades.add("Wenceslau Guimarães");
        this.cidades.add("Xique-Xique");
        this.cidades.add("Abaíra");
        this.cidades.add("Abaré");
        this.cidades.add("Acajutiba");
        this.cidades.add("Adustina");
        this.cidades.add("Água Fria");
        this.cidades.add("Érico Cardoso");
        this.cidades.add("Aiquara");
        this.cidades.add("Alagoinhas");
        this.cidades.add("Alcobaça");
        this.cidades.add("Almadina");
        this.cidades.add("Amargosa");
        this.cidades.add("Amélia Rodrigues");
        this.cidades.add("América Dourada");
        this.cidades.add("Anagé");
        this.cidades.add("Andaraí");
        this.cidades.add("Andorinha");
        this.cidades.add("Angical");
        this.cidades.add("Anguera");
        this.cidades.add("Antas");
        this.cidades.add("Antônio Cardoso");
        this.cidades.add("Antônio Gonçalves");
        this.cidades.add("Aporá");
        this.cidades.add("Apuarema");
        this.cidades.add("Aracatu");
        this.cidades.add("Araças");
        this.cidades.add("Araci");
        this.cidades.add("Aramari");
        this.cidades.add("Arataca");
        this.cidades.add("Aratuípe");
        this.cidades.add("Aurelino Leal");
        this.cidades.add("Baianópolis");
        this.cidades.add("Baixa Grande");
        this.cidades.add("Banzaê");
        this.cidades.add("Barra");
        this.cidades.add("Barra da Estiva");
        this.cidades.add("Barra do Choça");
        this.cidades.add("Barra do Mendes");
        this.cidades.add("Barra do Rocha");
        this.cidades.add("Barreiras");
        this.cidades.add("Barro Alto");
        this.cidades.add("Barrocas");
        this.cidades.add("Barro Preto");
        this.cidades.add("Belmonte");
        this.cidades.add("Belo Campo");
        this.cidades.add("Biritinga");
        this.cidades.add("Boa Nova");
        this.cidades.add("Boa Vista do Tupim");
        this.cidades.add("Bom Jesus da Lapa");
        this.cidades.add("Bom Jesus da Serra");
        this.cidades.add("Boninal");
        this.cidades.add("Bonito");
        this.cidades.add("Boquira");
        this.cidades.add("Botuporã");
        this.cidades.add("Brejões");
        this.cidades.add("Brejolândia");
        this.cidades.add("Brotas de Macaúbas");
        this.cidades.add("Brumado");
        this.cidades.add("Buerarema");
        this.cidades.add("Buritirama");
        this.cidades.add("Caatiba");
        this.cidades.add("Cabaceiras do Paraguaçu");
        this.cidades.add("Cachoeira");
        this.cidades.add("Caculé");
        this.cidades.add("Caém");
        this.cidades.add("Caetanos");
        this.cidades.add("Caetité");
        this.cidades.add("Cafarnaum");
        this.cidades.add("Cairu");
        this.cidades.add("Caldeirão Grande");
        this.cidades.add("Camacan");
        this.cidades.add("Camaçari");
        this.cidades.add("Camamu");
        this.cidades.add("Campo Alegre de Lourdes");
        this.cidades.add("Campo Formoso");
        this.cidades.add("Canápolis");
        this.cidades.add("Canarana");
        this.cidades.add("Canavieiras");
        this.cidades.add("Candeal");
        this.cidades.add("Candeias");
        this.cidades.add("Candiba");
        this.cidades.add("Cândido Sales");
        this.cidades.add("Cansanção");
        this.cidades.add("Canudos");
        this.cidades.add("Capela do Alto Alegre");
        this.cidades.add("Capim Grosso");
        this.cidades.add("Caraíbas");
        this.cidades.add("Caravelas");
        this.cidades.add("Cardeal da Silva");
        this.cidades.add("Carinhanha");
        this.cidades.add("Casa Nova");
        this.cidades.add("Castro Alves");
        this.cidades.add("Catolândia");
        this.cidades.add("Catu");
        this.cidades.add("Caturama");
        this.cidades.add("Central");
        this.cidades.add("Chorrochó");
        this.cidades.add("Cícero Dantas");
        this.cidades.add("Cipó");
        this.cidades.add("Coaraci");
        this.cidades.add("Cocos");
        this.cidades.add("Conceição da Feira");
        this.cidades.add("Conceição do Almeida");
        this.cidades.add("Conceição do Coité");
        this.cidades.add("Conceição do Jacuípe");
        this.cidades.add("Conde");
        this.cidades.add("Condeúba");
        this.cidades.add("Contendas do Sincorá");
        this.cidades.add("Coração de Maria");
        this.cidades.add("Cordeiros");
        this.cidades.add("Coribe");
        this.cidades.add("Coronel João Sá");
        this.cidades.add("Correntina");
        this.cidades.add("Cotegipe");
        this.cidades.add("Cravolândia");
        this.cidades.add("Crisópolis");
        this.cidades.add("Cristópolis");
        this.cidades.add("Cruz das Almas");
        this.cidades.add("Curaçá");
        this.cidades.add("Dário Meira");
        this.cidades.add("Dias D'Ávila");
        this.cidades.add("Dom Basílio");
        this.cidades.add("Dom Macedo Costa");
        this.cidades.add("Elísio Medrado");
        this.cidades.add("Encruzilhada");
        this.cidades.add("Entre Rios");
        this.cidades.add("Esplanada");
        this.cidades.add("Euclides da Cunha");
        this.cidades.add("Eunápolis");
        this.cidades.add("Fátima");
        this.cidades.add("Feira da Mata");
        this.cidades.add("Feira de Santana");
        this.cidades.add("Filadélfia");
        this.cidades.add("Firmino Alves");
        this.cidades.add("Floresta Azul");
        this.cidades.add("Formosa do Rio Preto");
        this.cidades.add("Gandu");
        this.cidades.add("Gavião");
        this.cidades.add("Gentio do Ouro");
        this.cidades.add("Glória");
        this.cidades.add("Gongogi");
        this.cidades.add("Governador Mangabeira");
        this.cidades.add("Guajeru");
        this.cidades.add("Guanambi");
        this.cidades.add("Guaratinga");
        this.cidades.add("Heliópolis");
        this.cidades.add("Iaçu");
        this.cidades.add("Ibiassucê");
        this.cidades.add("Ibicaraí");
        this.cidades.add("Ibicoara");
        this.cidades.add("Ibicuí");
        this.cidades.add("Ibipeba");
        this.cidades.add("Ibipitanga");
        this.cidades.add("Ibiquera");
        this.cidades.add("Ibirapitanga");
        this.cidades.add("Ibirapuã");
        this.cidades.add("Ibirataia");
        this.cidades.add("Ibitiara");
        this.cidades.add("Ibititá");
        this.cidades.add("Ibotirama");
        this.cidades.add("Ichu");
        this.cidades.add("Igaporã");
        this.cidades.add("Igrapiúna");
        this.cidades.add("Iguaí");
        this.cidades.add("Ilhéus");
        this.cidades.add("Inhambupe");
        this.cidades.add("Ipecaetá");
        this.cidades.add("Ipiaú");
        this.cidades.add("Ipirá");
        this.cidades.add("Ipupiara");
        this.cidades.add("Irajuba");
        this.cidades.add("Iramaia");
        this.cidades.add("Iraquara");
        this.cidades.add("Irará");
        this.cidades.add("Irecê");
        this.cidades.add("Itabela");
        this.cidades.add("Itaberaba");
        this.cidades.add("Itabuna");
        this.cidades.add("Itacaré");
        this.cidades.add("Itaeté");
        this.cidades.add("Itagi");
        this.cidades.add("Itagibá");
        this.cidades.add("Itagimirim");
        this.cidades.add("Itaguaçu da Bahia");
        this.cidades.add("Itaju do Colônia");
        this.cidades.add("Itajuípe");
        this.cidades.add("Itamaraju");
        this.cidades.add("Itamari");
        this.cidades.add("Itambé");
        this.cidades.add("Itanagra");
        this.cidades.add("Itanhém");
        this.cidades.add("Itaparica");
        this.cidades.add("Itapé");
        this.cidades.add("Itapebi");
        this.cidades.add("Itapetinga");
        this.cidades.add("Itapicuru");
        this.cidades.add("Itapitanga");
        this.cidades.add("Itaquara");
        this.cidades.add("Itarantim");
        this.cidades.add("Itatim");
        this.cidades.add("Itiruçu");
        this.cidades.add("Itiúba");
        this.cidades.add("Itororó");
        this.cidades.add("Ituaçu");
        this.cidades.add("Ituberá");
        this.cidades.add("Iuiú");
        this.cidades.add("Jaborandi");
        this.cidades.add("Jacaraci");
        this.cidades.add("Jacobina");
        this.cidades.add("Jaguaquara");
        this.cidades.add("Jaguarari");
        this.cidades.add("Jaguaripe");
        this.cidades.add("Jandaíra");
        this.cidades.add("Jequié");
        this.cidades.add("Jeremoabo");
        this.cidades.add("Jiquiriçá");
        this.cidades.add("Jitaúna");
        this.cidades.add("João Dourado");
        this.cidades.add("Juazeiro");
        this.cidades.add("Jucuruçu");
        this.cidades.add("Jussara");
        this.cidades.add("Jussari");
        this.cidades.add("Jussiape");
        this.cidades.add("Lafaiete Coutinho");
        this.cidades.add("Lagoa Real");
        this.cidades.add("Laje");
        this.cidades.add("Lajedão");
        this.cidades.add("Lajedinho");
        this.cidades.add("Lajedo do Tabocal");
        this.cidades.add("Lamarão");
        this.cidades.add("Lapão");
        this.cidades.add("Lauro de Freitas");
        this.cidades.add("Lençóis");
        this.cidades.add("Licínio de Almeida");
        this.cidades.add("Livramento de Nossa Senhora");
        this.cidades.add("Luís Eduardo Magalhães");
        this.cidades.add("Macajuba");
        this.cidades.add("Macarani");
        this.cidades.add("Macaúbas");
        this.cidades.add("Macururé");
        this.cidades.add("Madre de Deus");
        this.cidades.add("Maetinga");
        this.cidades.add("Maiquinique");
        this.cidades.add("Mairi");
        this.cidades.add("Malhada");
        this.cidades.add("Malhada de Pedras");
        this.cidades.add("Manoel Vitorino");
        this.cidades.add("Mansidão");
        this.cidades.add("Maracás");
        this.cidades.add("Maragogipe");
        this.cidades.add("Maraú");
        this.cidades.add("Marcionílio Souza");
        this.cidades.add("Mascote");
        this.cidades.add("Mata de São João");
        this.cidades.add("Matina");
        this.cidades.add("Medeiros Neto");
        this.cidades.add("Miguel Calmon");
        this.cidades.add("Milagres");
        this.cidades.add("Mirangaba");
        this.cidades.add("Mirante");
        this.cidades.add("Monte Santo");
        this.cidades.add("Morpará");
        this.cidades.add("Morro do Chapéu");
        this.cidades.add("Mortugaba");
        this.cidades.add("Mucugê");
        this.cidades.add("Mucuri");
        this.cidades.add("Mulungu do Morro");
        this.cidades.add("Mundo Novo");
        this.cidades.add("Muniz Ferreira");
        this.cidades.add("Muquém de São Francisco");
        this.cidades.add("Muritiba");
        this.cidades.add("Mutuípe");
        this.cidades.add("Nazaré");
        this.cidades.add("Nilo Peçanha");
        this.cidades.add("Nordestina");
        this.cidades.add("Nova Canaã");
        this.cidades.add("Nova Fátima");
        this.cidades.add("Nova Ibiá");
        this.cidades.add("Nova Itarana");
        this.cidades.add("Nova Redenção");
        this.cidades.add("Nova Soure");
        this.cidades.add("Nova Viçosa");
        this.cidades.add("Novo Horizonte");
        this.cidades.add("Novo Triunfo");
        this.cidades.add("Olindina");
        this.cidades.add("Oliveira dos Brejinhos");
        this.cidades.add("Ouriçangas");
        this.cidades.add("Ourolândia");
        this.cidades.add("Palmas de Monte Alto");
        this.cidades.add("Palmeiras");
        this.cidades.add("Paramirim");
        this.cidades.add("Paratinga");
        this.cidades.add("Paripiranga");
        this.cidades.add("Pau Brasil");
        this.cidades.add("Paulo Afonso");
        this.cidades.add("Pé de Serra");
        this.cidades.add("Pedrão");
        this.cidades.add("Pedro Alexandre");
        this.cidades.add("Piatã");
        this.cidades.add("Pilão Arcado");
        this.cidades.add("Pindaí");
        this.cidades.add("Pindobaçu");
        this.cidades.add("Pintadas");
        this.cidades.add("Piraí do Norte");
        this.cidades.add("Piripá");
        this.cidades.add("Piritiba");
        this.cidades.add("Planaltino");
        this.cidades.add("Planalto");
        this.cidades.add("Poções");
        this.cidades.add("Pojuca");
        this.cidades.add("Ponto Novo");
        this.cidades.add("Porto Seguro");
        this.cidades.add("Potiraguá");
        this.cidades.add("Prado");
        this.cidades.add("Presidente Dutra");
        this.cidades.add("Presidente Jânio Quadros");
        this.cidades.add("Presidente Tancredo Neves");
        this.cidades.add("Queimadas");
        this.cidades.add("Quijingue");
        this.cidades.add("Quixabeira");
        this.cidades.add("Rafael Jambeiro");
        this.cidades.add("Remanso");
        this.cidades.add("Retirolândia");
        this.cidades.add("Riachão das Neves");
        this.cidades.add("Riachão do Jacuípe");
        this.cidades.add("Riacho de Santana");
        this.cidades.add("Ribeira do Amparo");
        this.cidades.add("Ribeira do Pombal");
        this.cidades.add("Ribeirão do Largo");
        this.cidades.add("Rio de Contas");
        this.cidades.add("Rio do Antônio");
        this.cidades.add("Rio do Pires");
        this.cidades.add("Rio Real");
        this.cidades.add("Rodelas");
        this.cidades.add("Ruy Barbosa");
        this.cidades.add("Salinas da Margarida");
        this.cidades.add("Salvador");
        this.cidades.add("Santa Bárbara");
        this.cidades.add("Santa Brígida");
        this.cidades.add("Santa Cruz Cabrália");
        this.cidades.add("Santa Cruz da Vitória");
        this.cidades.add("Santa Inês");
        this.cidades.add("Santaluz");
        this.cidades.add("Santa Luzia");
        this.cidades.add("Santa Maria da Vitória");
        this.cidades.add("Santana");
        this.cidades.add("Santanópolis");
        this.cidades.add("Santa Rita de Cássia");
        this.cidades.add("Santa Teresinha");
        this.cidades.add("Santo Amaro");
        this.cidades.add("Santo Antônio de Jesus");
        this.cidades.add("Santo Estêvão");
        this.cidades.add("São Desidério");
        this.cidades.add("São Domingos");
        this.cidades.add("São Félix");
        this.cidades.add("São Félix do Coribe");
        this.cidades.add("São Felipe");
        this.cidades.add("São Francisco do Conde");
        this.cidades.add("São Gabriel");
        this.cidades.add("São Gonçalo dos Campos");
        this.cidades.add("São José da Vitória");
        this.cidades.add("São José do Jacuípe");
        this.cidades.add("São Miguel das Matas");
        this.cidades.add("São Sebastião do Passé");
        this.cidades.add("Sapeaçu");
        this.cidades.add("Sátiro Dias");
        this.cidades.add("Saubara");
        this.cidades.add("Saúde");
        this.cidades.add("Seabra");
        this.cidades.add("Sebastião Laranjeiras");
        this.cidades.add("Senhor do Bonfim");
        this.cidades.add("Serra do Ramalho");
        this.cidades.add("Sento Sé");
        this.cidades.add("Serra Dourada");
        this.cidades.add("Serra Preta");
        this.cidades.add("Serrinha");
        this.cidades.add("Serrolândia");
        this.cidades.add("Simões Filho");
        this.cidades.add("Sítio do Mato");
        this.cidades.add("Sítio do Quinto");
        this.cidades.add("Sobradinho");
        this.cidades.add("Souto Soares");
        this.cidades.add("Tabocas do Brejo Velho");
        this.cidades.add("Tanhaçu");
        this.cidades.add("Tanque Novo");
        this.cidades.add("Tanquinho");
        this.cidades.add("Taperoá");
        this.cidades.add("Tapiramutá");
        this.cidades.add("Teixeira de Freitas");
        this.cidades.add("Teodoro Sampaio");
        this.cidades.add("Teofilândia");
        this.cidades.add("Teolândia");
        this.cidades.add("Terra Nova");
        this.cidades.add("Tremedal");
        this.cidades.add("Tucano");
        this.cidades.add("Uauá");
        this.cidades.add("Ubaíra");
        this.cidades.add("Ubaitaba");
        this.cidades.add("Ubatã");
        this.cidades.add("Uibaí");
        this.cidades.add("Umburanas");
        this.cidades.add("Una");
        this.cidades.add("Urandi");
        this.cidades.add("Uruçuca");
        this.cidades.add("Utinga");
        this.cidades.add("Valença");
        this.cidades.add("Valente");
        this.cidades.add("Várzea da Roça");
        this.cidades.add("Várzea do Poço");
        this.cidades.add("Várzea Nova");
        this.cidades.add("Varzedo");
        this.cidades.add("Vera Cruz");
        this.cidades.add("Vereda");
        this.cidades.add("Vitória da Conquista");
        this.cidades.add("Wagner");
        this.cidades.add("Wanderley");
        this.cidades.add("Wenceslau Guimarães");
        this.cidades.add("Xique-Xique");


        return  cidades;
    }

}
