package com.igor.listviewclick.EstadosCidades;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Igor on 18/03/2018.
 */

public class CE {

    List<String> cidades = new ArrayList<>();

    public CE() {}

    public List<String> getCidades() {

        this.cidades.add("Abaiara");
        this.cidades.add("Acarape");
        this.cidades.add("Acaraú");
        this.cidades.add("Acopiara");
        this.cidades.add("Aiuaba");
        this.cidades.add("Alcântaras");
        this.cidades.add("Altaneira");
        this.cidades.add("Alto Santo");
        this.cidades.add("Amontada");
        this.cidades.add("Antonina do Norte");
        this.cidades.add("Apuiarés");
        this.cidades.add("Aquiraz");
        this.cidades.add("Aracati");
        this.cidades.add("Aracoiaba");
        this.cidades.add("Ararendá");
        this.cidades.add("Araripe");
        this.cidades.add("Aratuba");
        this.cidades.add("Arneiroz");
        this.cidades.add("Assaré");
        this.cidades.add("Aurora");
        this.cidades.add("Baixio");
        this.cidades.add("Banabuiú");
        this.cidades.add("Barbalha");
        this.cidades.add("Barreira");
        this.cidades.add("Barro");
        this.cidades.add("Barroquinha");
        this.cidades.add("Baturité");
        this.cidades.add("Beberibe");
        this.cidades.add("Bela Cruz");
        this.cidades.add("Boa Viagem");
        this.cidades.add("Brejo Santo");
        this.cidades.add("Camocim");
        this.cidades.add("Campos Sales");
        this.cidades.add("Canindé");
        this.cidades.add("Capistrano");
        this.cidades.add("Caridade");
        this.cidades.add("Cariré");
        this.cidades.add("Caririaçu");
        this.cidades.add("Cariús");
        this.cidades.add("Carnaubal");
        this.cidades.add("Cascavel");
        this.cidades.add("Catarina");
        this.cidades.add("Catunda");
        this.cidades.add("Caucaia");
        this.cidades.add("Cedro");
        this.cidades.add("Chaval");
        this.cidades.add("Choró");
        this.cidades.add("Chorozinho");
        this.cidades.add("Coreaú");
        this.cidades.add("Crateús");
        this.cidades.add("Crato");
        this.cidades.add("Croatá");
        this.cidades.add("Cruz");
        this.cidades.add("Deputado Irapuan Pinheiro");
        this.cidades.add("Ererê");
        this.cidades.add("Eusébio");
        this.cidades.add("Farias Brito");
        this.cidades.add("Forquilha");
        this.cidades.add("Fortaleza");
        this.cidades.add("Fortim");
        this.cidades.add("Frecheirinha");
        this.cidades.add("General Sampaio");
        this.cidades.add("Graça");
        this.cidades.add("Granja");
        this.cidades.add("Granjeiro");
        this.cidades.add("Groaíras");
        this.cidades.add("Guaiúba");
        this.cidades.add("Guaraciaba do Norte");
        this.cidades.add("Guaramiranga");
        this.cidades.add("Hidrolândia");
        this.cidades.add("Horizonte");
        this.cidades.add("Ibaretama");
        this.cidades.add("Ibiapina");
        this.cidades.add("Ibicuitinga");
        this.cidades.add("Icapuí");
        this.cidades.add("Icó");
        this.cidades.add("Iguatu");
        this.cidades.add("Independência");
        this.cidades.add("Ipaporanga");
        this.cidades.add("Ipaumirim");
        this.cidades.add("Ipu");
        this.cidades.add("Ipueiras");
        this.cidades.add("Iracema");
        this.cidades.add("Irauçuba");
        this.cidades.add("Itaiçaba");
        this.cidades.add("Itaitinga");
        this.cidades.add("Itapagé");
        this.cidades.add("Itapipoca");
        this.cidades.add("Itapiúna");
        this.cidades.add("Itarema");
        this.cidades.add("Itatira");
        this.cidades.add("Jaguaretama");
        this.cidades.add("Jaguaribara");
        this.cidades.add("Jaguaribe");
        this.cidades.add("Jaguaruana");
        this.cidades.add("Jardim");
        this.cidades.add("Jati");
        this.cidades.add("Jijoca de Jericoacoara");
        this.cidades.add("Juazeiro do Norte");
        this.cidades.add("Jucás");
        this.cidades.add("Lavras da Mangabeira");
        this.cidades.add("Limoeiro do Norte");
        this.cidades.add("Madalena");
        this.cidades.add("Maracanaú");
        this.cidades.add("Maranguape");
        this.cidades.add("Marco");
        this.cidades.add("Martinópole");
        this.cidades.add("Massapê");
        this.cidades.add("Mauriti");
        this.cidades.add("Meruoca");
        this.cidades.add("Milagres");
        this.cidades.add("Milhã");
        this.cidades.add("Miraíma");
        this.cidades.add("Missão Velha");
        this.cidades.add("Mombaça");
        this.cidades.add("Monsenhor Tabosa");
        this.cidades.add("Morada Nova");
        this.cidades.add("Moraújo");
        this.cidades.add("Morrinhos");
        this.cidades.add("Mucambo");
        this.cidades.add("Mulungu");
        this.cidades.add("Nova Olinda");
        this.cidades.add("Nova Russas");
        this.cidades.add("Novo Oriente");
        this.cidades.add("Ocara");
        this.cidades.add("Orós");
        this.cidades.add("Pacajus");
        this.cidades.add("Pacatuba");
        this.cidades.add("Pacoti");
        this.cidades.add("Pacujá");
        this.cidades.add("Palhano");
        this.cidades.add("Palmácia");
        this.cidades.add("Paracuru");
        this.cidades.add("Paraipaba");
        this.cidades.add("Parambu");
        this.cidades.add("Paramoti");
        this.cidades.add("Pedra Branca");
        this.cidades.add("Penaforte");
        this.cidades.add("Pentecoste");
        this.cidades.add("Pereiro");
        this.cidades.add("Pindoretama");
        this.cidades.add("Piquet Carneiro");
        this.cidades.add("Pires Ferreira");
        this.cidades.add("Poranga");
        this.cidades.add("Porteiras");
        this.cidades.add("Potengi");
        this.cidades.add("Potiretama");
        this.cidades.add("Quiterianópolis");
        this.cidades.add("Quixadá");
        this.cidades.add("Quixelô");
        this.cidades.add("Quixeramobim");
        this.cidades.add("Quixeré");
        this.cidades.add("Redenção");
        this.cidades.add("Reriutaba");
        this.cidades.add("Russas");
        this.cidades.add("Saboeiro");
        this.cidades.add("Salitre");
        this.cidades.add("Santana do Acaraú");
        this.cidades.add("Santana do Cariri");
        this.cidades.add("Santa Quitéria");
        this.cidades.add("São Benedito");
        this.cidades.add("São Gonçalo do Amarante");
        this.cidades.add("São João do Jaguaribe");
        this.cidades.add("São Luís do Curu");
        this.cidades.add("Senador Pompeu");
        this.cidades.add("Senador Sá");
        this.cidades.add("Sobral");
        this.cidades.add("Solonópole");
        this.cidades.add("Tabuleiro do Norte");
        this.cidades.add("Tamboril");
        this.cidades.add("Tarrafas");
        this.cidades.add("Tauá");
        this.cidades.add("Tejuçuoca");
        this.cidades.add("Tianguá");
        this.cidades.add("Trairi");
        this.cidades.add("Tururu");
        this.cidades.add("Ubajara");
        this.cidades.add("Umari");
        this.cidades.add("Umirim");
        this.cidades.add("Uruburetama");
        this.cidades.add("Uruoca");
        this.cidades.add("Varjota");
        this.cidades.add("Várzea Alegre");
        this.cidades.add("Viçosa do Ceará");
        this.cidades.add("Abaiara");
        this.cidades.add("Acarape");
        this.cidades.add("Acaraú");
        this.cidades.add("Acopiara");
        this.cidades.add("Aiuaba");
        this.cidades.add("Alcântaras");
        this.cidades.add("Altaneira");
        this.cidades.add("Alto Santo");
        this.cidades.add("Amontada");
        this.cidades.add("Antonina do Norte");
        this.cidades.add("Apuiarés");
        this.cidades.add("Aquiraz");
        this.cidades.add("Aracati");
        this.cidades.add("Aracoiaba");
        this.cidades.add("Ararendá");
        this.cidades.add("Araripe");
        this.cidades.add("Aratuba");
        this.cidades.add("Arneiroz");
        this.cidades.add("Assaré");
        this.cidades.add("Aurora");
        this.cidades.add("Baixio");
        this.cidades.add("Banabuiú");
        this.cidades.add("Barbalha");
        this.cidades.add("Barreira");
        this.cidades.add("Barro");
        this.cidades.add("Barroquinha");
        this.cidades.add("Baturité");
        this.cidades.add("Beberibe");
        this.cidades.add("Bela Cruz");
        this.cidades.add("Boa Viagem");
        this.cidades.add("Brejo Santo");
        this.cidades.add("Camocim");
        this.cidades.add("Campos Sales");
        this.cidades.add("Canindé");
        this.cidades.add("Capistrano");
        this.cidades.add("Caridade");
        this.cidades.add("Cariré");
        this.cidades.add("Caririaçu");
        this.cidades.add("Cariús");
        this.cidades.add("Carnaubal");
        this.cidades.add("Cascavel");
        this.cidades.add("Catarina");
        this.cidades.add("Catunda");
        this.cidades.add("Caucaia");
        this.cidades.add("Cedro");
        this.cidades.add("Chaval");
        this.cidades.add("Choró");
        this.cidades.add("Chorozinho");
        this.cidades.add("Coreaú");
        this.cidades.add("Crateús");
        this.cidades.add("Crato");
        this.cidades.add("Croatá");
        this.cidades.add("Cruz");
        this.cidades.add("Deputado Irapuan Pinheiro");
        this.cidades.add("Ererê");
        this.cidades.add("Eusébio");
        this.cidades.add("Farias Brito");
        this.cidades.add("Forquilha");
        this.cidades.add("Fortaleza");
        this.cidades.add("Fortim");
        this.cidades.add("Frecheirinha");
        this.cidades.add("General Sampaio");
        this.cidades.add("Graça");
        this.cidades.add("Granja");
        this.cidades.add("Granjeiro");
        this.cidades.add("Groaíras");
        this.cidades.add("Guaiúba");
        this.cidades.add("Guaraciaba do Norte");
        this.cidades.add("Guaramiranga");
        this.cidades.add("Hidrolândia");
        this.cidades.add("Horizonte");
        this.cidades.add("Ibaretama");
        this.cidades.add("Ibiapina");
        this.cidades.add("Ibicuitinga");
        this.cidades.add("Icapuí");
        this.cidades.add("Icó");
        this.cidades.add("Iguatu");
        this.cidades.add("Independência");
        this.cidades.add("Ipaporanga");
        this.cidades.add("Ipaumirim");
        this.cidades.add("Ipu");
        this.cidades.add("Ipueiras");
        this.cidades.add("Iracema");
        this.cidades.add("Irauçuba");
        this.cidades.add("Itaiçaba");
        this.cidades.add("Itaitinga");
        this.cidades.add("Itapagé");
        this.cidades.add("Itapipoca");
        this.cidades.add("Itapiúna");
        this.cidades.add("Itarema");
        this.cidades.add("Itatira");
        this.cidades.add("Jaguaretama");
        this.cidades.add("Jaguaribara");
        this.cidades.add("Jaguaribe");
        this.cidades.add("Jaguaruana");
        this.cidades.add("Jardim");
        this.cidades.add("Jati");
        this.cidades.add("Jijoca de Jericoacoara");
        this.cidades.add("Juazeiro do Norte");
        this.cidades.add("Jucás");
        this.cidades.add("Lavras da Mangabeira");
        this.cidades.add("Limoeiro do Norte");
        this.cidades.add("Madalena");
        this.cidades.add("Maracanaú");
        this.cidades.add("Maranguape");
        this.cidades.add("Marco");
        this.cidades.add("Martinópole");
        this.cidades.add("Massapê");
        this.cidades.add("Mauriti");
        this.cidades.add("Meruoca");
        this.cidades.add("Milagres");
        this.cidades.add("Milhã");
        this.cidades.add("Miraíma");
        this.cidades.add("Missão Velha");
        this.cidades.add("Mombaça");
        this.cidades.add("Monsenhor Tabosa");
        this.cidades.add("Morada Nova");
        this.cidades.add("Moraújo");
        this.cidades.add("Morrinhos");
        this.cidades.add("Mucambo");
        this.cidades.add("Mulungu");
        this.cidades.add("Nova Olinda");
        this.cidades.add("Nova Russas");
        this.cidades.add("Novo Oriente");
        this.cidades.add("Ocara");
        this.cidades.add("Orós");
        this.cidades.add("Pacajus");
        this.cidades.add("Pacatuba");
        this.cidades.add("Pacoti");
        this.cidades.add("Pacujá");
        this.cidades.add("Palhano");
        this.cidades.add("Palmácia");
        this.cidades.add("Paracuru");
        this.cidades.add("Paraipaba");
        this.cidades.add("Parambu");
        this.cidades.add("Paramoti");
        this.cidades.add("Pedra Branca");
        this.cidades.add("Penaforte");
        this.cidades.add("Pentecoste");
        this.cidades.add("Pereiro");
        this.cidades.add("Pindoretama");
        this.cidades.add("Piquet Carneiro");
        this.cidades.add("Pires Ferreira");
        this.cidades.add("Poranga");
        this.cidades.add("Porteiras");
        this.cidades.add("Potengi");
        this.cidades.add("Potiretama");
        this.cidades.add("Quiterianópolis");
        this.cidades.add("Quixadá");
        this.cidades.add("Quixelô");
        this.cidades.add("Quixeramobim");
        this.cidades.add("Quixeré");
        this.cidades.add("Redenção");
        this.cidades.add("Reriutaba");
        this.cidades.add("Russas");
        this.cidades.add("Saboeiro");
        this.cidades.add("Salitre");
        this.cidades.add("Santana do Acaraú");
        this.cidades.add("Santana do Cariri");
        this.cidades.add("Santa Quitéria");
        this.cidades.add("São Benedito");
        this.cidades.add("São Gonçalo do Amarante");
        this.cidades.add("São João do Jaguaribe");
        this.cidades.add("São Luís do Curu");
        this.cidades.add("Senador Pompeu");
        this.cidades.add("Senador Sá");
        this.cidades.add("Sobral");
        this.cidades.add("Solonópole");
        this.cidades.add("Tabuleiro do Norte");
        this.cidades.add("Tamboril");
        this.cidades.add("Tarrafas");
        this.cidades.add("Tauá");
        this.cidades.add("Tejuçuoca");
        this.cidades.add("Tianguá");
        this.cidades.add("Trairi");
        this.cidades.add("Tururu");
        this.cidades.add("Ubajara");
        this.cidades.add("Umari");
        this.cidades.add("Umirim");
        this.cidades.add("Uruburetama");
        this.cidades.add("Uruoca");
        this.cidades.add("Varjota");
        this.cidades.add("Várzea Alegre");
        this.cidades.add("Viçosa do Ceará");

        return cidades;
    }
}
