package com.igor.listviewclick.EstadosCidades;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Igor on 18/03/2018.
 */

public class GO {

    List<String> cidades = new ArrayList<>();

    public GO() {}

    public List<String> getCidades() {

        this.cidades.add("Abadia de Goiás");
        this.cidades.add("Abadiânia");
        this.cidades.add("Acreúna");
        this.cidades.add("Adelândia");
        this.cidades.add("Água Fria de Goiás");
        this.cidades.add("Água Limpa");
        this.cidades.add("Águas Lindas de Goiás");
        this.cidades.add("Alexânia");
        this.cidades.add("Aloândia");
        this.cidades.add("Alto Horizonte");
        this.cidades.add("Alto Paraíso de Goiás");
        this.cidades.add("Alvorada do Norte");
        this.cidades.add("Amaralina");
        this.cidades.add("Americano do Brasil");
        this.cidades.add("Amorinópolis");
        this.cidades.add("Anápolis");
        this.cidades.add("Anhanguera");
        this.cidades.add("Anicuns");
        this.cidades.add("Aparecida de Goiânia");
        this.cidades.add("Aparecida do Rio Doce");
        this.cidades.add("Aporé");
        this.cidades.add("Araçu");
        this.cidades.add("Aragarças");
        this.cidades.add("Aragoiânia");
        this.cidades.add("Araguapaz");
        this.cidades.add("Arenópolis");
        this.cidades.add("Aruanã");
        this.cidades.add("Aurilândia");
        this.cidades.add("Avelinópolis");
        this.cidades.add("Baliza");
        this.cidades.add("Barro Alto");
        this.cidades.add("Bela Vista de Goiás");
        this.cidades.add("Bom Jardim de Goiás");
        this.cidades.add("Bom Jesus de Goiás");
        this.cidades.add("Bonfinópolis");
        this.cidades.add("Bonópolis");
        this.cidades.add("Brazabrantes");
        this.cidades.add("Britânia");
        this.cidades.add("Buriti Alegre");
        this.cidades.add("Buriti de Goiás");
        this.cidades.add("Buritinópolis");
        this.cidades.add("Cabeceiras");
        this.cidades.add("Cachoeira Alta");
        this.cidades.add("Cachoeira de Goiás");
        this.cidades.add("Cachoeira Dourada");
        this.cidades.add("Caçu");
        this.cidades.add("Caiapônia");
        this.cidades.add("Caldas Novas");
        this.cidades.add("Caldazinha");
        this.cidades.add("Campestre de Goiás");
        this.cidades.add("Campinaçu");
        this.cidades.add("Campinorte");
        this.cidades.add("Campo Alegre de Goiás");
        this.cidades.add("Campo Limpo de Goiás");
        this.cidades.add("Campos Belos");
        this.cidades.add("Campos Verdes");
        this.cidades.add("Carmo do Rio Verde");
        this.cidades.add("Castelândia");
        this.cidades.add("Catalão");
        this.cidades.add("Caturaí");
        this.cidades.add("Cavalcante");
        this.cidades.add("Ceres");
        this.cidades.add("Cezarina");
        this.cidades.add("Chapadão do Céu");
        this.cidades.add("Cidade Ocidental");
        this.cidades.add("Cocalzinho de Goiás");
        this.cidades.add("Colinas do Sul");
        this.cidades.add("Córrego do Ouro");
        this.cidades.add("Corumbá de Goiás");
        this.cidades.add("Corumbaíba");
        this.cidades.add("Cristalina");
        this.cidades.add("Cristianópolis");
        this.cidades.add("Crixás");
        this.cidades.add("Cromínia");
        this.cidades.add("Cumari");
        this.cidades.add("Damianópolis");
        this.cidades.add("Damolândia");
        this.cidades.add("Davinópolis");
        this.cidades.add("Diorama");
        this.cidades.add("Doverlândia");
        this.cidades.add("Edealina");
        this.cidades.add("Edéia");
        this.cidades.add("Estrela do Norte");
        this.cidades.add("Faina");
        this.cidades.add("Fazenda Nova");
        this.cidades.add("Firminópolis");
        this.cidades.add("Flores de Goiás");
        this.cidades.add("Formosa");
        this.cidades.add("Formoso");
        this.cidades.add("Gameleira de Goiás");
        this.cidades.add("Divinópolis de Goiás");
        this.cidades.add("Goianápolis");
        this.cidades.add("Goiandira");
        this.cidades.add("Goianésia");
        this.cidades.add("Goiânia");
        this.cidades.add("Goianira");
        this.cidades.add("Goiás");
        this.cidades.add("Goiatuba");
        this.cidades.add("Gouvelândia");
        this.cidades.add("Guapó");
        this.cidades.add("Guaraíta");
        this.cidades.add("Guarani de Goiás");
        this.cidades.add("Guarinos");
        this.cidades.add("Heitoraí");
        this.cidades.add("Hidrolândia");
        this.cidades.add("Hidrolina");
        this.cidades.add("Iaciara");
        this.cidades.add("Inaciolândia");
        this.cidades.add("Indiara");
        this.cidades.add("Inhumas");
        this.cidades.add("Ipameri");
        this.cidades.add("Ipiranga de Goiás");
        this.cidades.add("Iporá");
        this.cidades.add("Israelândia");
        this.cidades.add("Itaberaí");
        this.cidades.add("Itaguari");
        this.cidades.add("Itaguaru");
        this.cidades.add("Itajá");
        this.cidades.add("Itapaci");
        this.cidades.add("Itapirapuã");
        this.cidades.add("Itapuranga");
        this.cidades.add("Itarumã");
        this.cidades.add("Itauçu");
        this.cidades.add("Itumbiara");
        this.cidades.add("Ivolândia");
        this.cidades.add("Jandaia");
        this.cidades.add("Jaraguá");
        this.cidades.add("Jataí");
        this.cidades.add("Jaupaci");
        this.cidades.add("Jesúpolis");
        this.cidades.add("Joviânia");
        this.cidades.add("Jussara");
        this.cidades.add("Lagoa Santa");
        this.cidades.add("Leopoldo de Bulhões");
        this.cidades.add("Luziânia");
        this.cidades.add("Mairipotaba");
        this.cidades.add("Mambaí");
        this.cidades.add("Mara Rosa");
        this.cidades.add("Marzagão");
        this.cidades.add("Matrinchã");
        this.cidades.add("Maurilândia");
        this.cidades.add("Mimoso de Goiás");
        this.cidades.add("Minaçu");
        this.cidades.add("Mineiros");
        this.cidades.add("Moiporá");
        this.cidades.add("Monte Alegre de Goiás");
        this.cidades.add("Montes Claros de Goiás");
        this.cidades.add("Montividiu");
        this.cidades.add("Montividiu do Norte");
        this.cidades.add("Morrinhos");
        this.cidades.add("Morro Agudo de Goiás");
        this.cidades.add("Mossâmedes");
        this.cidades.add("Mozarlândia");
        this.cidades.add("Mundo Novo");
        this.cidades.add("Mutunópolis");
        this.cidades.add("Nazário");
        this.cidades.add("Nerópolis");
        this.cidades.add("Niquelândia");
        this.cidades.add("Nova América");
        this.cidades.add("Nova Aurora");
        this.cidades.add("Nova Crixás");
        this.cidades.add("Nova Glória");
        this.cidades.add("Nova Iguaçu de Goiás");
        this.cidades.add("Nova Roma");
        this.cidades.add("Nova Veneza");
        this.cidades.add("Novo Brasil");
        this.cidades.add("Novo Gama");
        this.cidades.add("Novo Planalto");
        this.cidades.add("Orizona");
        this.cidades.add("Ouro Verde de Goiás");
        this.cidades.add("Ouvidor");
        this.cidades.add("Padre Bernardo");
        this.cidades.add("Palestina de Goiás");
        this.cidades.add("Palmeiras de Goiás");
        this.cidades.add("Palmelo");
        this.cidades.add("Palminópolis");
        this.cidades.add("Panamá");
        this.cidades.add("Paranaiguara");
        this.cidades.add("Paraúna");
        this.cidades.add("Perolândia");
        this.cidades.add("Petrolina de Goiás");
        this.cidades.add("Pilar de Goiás");
        this.cidades.add("Piracanjuba");
        this.cidades.add("Piranhas");
        this.cidades.add("Pirenópolis");
        this.cidades.add("Pires do Rio");
        this.cidades.add("Planaltina");
        this.cidades.add("Pontalina");
        this.cidades.add("Porangatu");
        this.cidades.add("Porteirão");
        this.cidades.add("Portelândia");
        this.cidades.add("Posse");
        this.cidades.add("Professor Jamil");
        this.cidades.add("Quirinópolis");
        this.cidades.add("Rialma");
        this.cidades.add("Rianápolis");
        this.cidades.add("Rio Quente");
        this.cidades.add("Rio Verde");
        this.cidades.add("Rubiataba");
        this.cidades.add("Sanclerlândia");
        this.cidades.add("Santa Bárbara de Goiás");
        this.cidades.add("Santa Cruz de Goiás");
        this.cidades.add("Santa Fé de Goiás");
        this.cidades.add("Santa Helena de Goiás");
        this.cidades.add("Santa Isabel");
        this.cidades.add("Santa Rita do Araguaia");
        this.cidades.add("Santa Rita do Novo Destino");
        this.cidades.add("Santa Rosa de Goiás");
        this.cidades.add("Santa Tereza de Goiás");
        this.cidades.add("Santa Terezinha de Goiás");
        this.cidades.add("Santo Antônio da Barra");
        this.cidades.add("Santo Antônio de Goiás");
        this.cidades.add("Santo Antônio do Descoberto");
        this.cidades.add("São Domingos");
        this.cidades.add("São Francisco de Goiás");
        this.cidades.add("São João D'Aliança");
        this.cidades.add("São João da Paraúna");
        this.cidades.add("São Luís de Montes Belos");
        this.cidades.add("São Luíz do Norte");
        this.cidades.add("São Miguel do Araguaia");
        this.cidades.add("São Miguel do Passa Quatro");
        this.cidades.add("São Patrício");
        this.cidades.add("São Simão");
        this.cidades.add("Senador Canedo");
        this.cidades.add("Serranópolis");
        this.cidades.add("Silvânia");
        this.cidades.add("Simolândia");
        this.cidades.add("Sítio D'Abadia");
        this.cidades.add("Taquaral de Goiás");
        this.cidades.add("Teresina de Goiás");
        this.cidades.add("Terezópolis de Goiás");
        this.cidades.add("Três Ranchos");
        this.cidades.add("Trindade");
        this.cidades.add("Trombas");
        this.cidades.add("Turvânia");
        this.cidades.add("Turvelândia");
        this.cidades.add("Uirapuru");
        this.cidades.add("Uruaçu");
        this.cidades.add("Uruana");
        this.cidades.add("Urutaí");
        this.cidades.add("Valparaíso de Goiás");
        this.cidades.add("Varjão");
        this.cidades.add("Vianópolis");
        this.cidades.add("Vicentinópolis");
        this.cidades.add("Vila Boa");
        this.cidades.add("Vila Propício");
        this.cidades.add("Abadia de Goiás");
        this.cidades.add("Abadiânia");
        this.cidades.add("Acreúna");
        this.cidades.add("Adelândia");
        this.cidades.add("Água Fria de Goiás");
        this.cidades.add("Água Limpa");
        this.cidades.add("Águas Lindas de Goiás");
        this.cidades.add("Alexânia");
        this.cidades.add("Aloândia");
        this.cidades.add("Alto Horizonte");
        this.cidades.add("Alto Paraíso de Goiás");
        this.cidades.add("Alvorada do Norte");
        this.cidades.add("Amaralina");
        this.cidades.add("Americano do Brasil");
        this.cidades.add("Amorinópolis");
        this.cidades.add("Anápolis");
        this.cidades.add("Anhanguera");
        this.cidades.add("Anicuns");
        this.cidades.add("Aparecida de Goiânia");
        this.cidades.add("Aparecida do Rio Doce");
        this.cidades.add("Aporé");
        this.cidades.add("Araçu");
        this.cidades.add("Aragarças");
        this.cidades.add("Aragoiânia");
        this.cidades.add("Araguapaz");
        this.cidades.add("Arenópolis");
        this.cidades.add("Aruanã");
        this.cidades.add("Aurilândia");
        this.cidades.add("Avelinópolis");
        this.cidades.add("Baliza");
        this.cidades.add("Barro Alto");
        this.cidades.add("Bela Vista de Goiás");
        this.cidades.add("Bom Jardim de Goiás");
        this.cidades.add("Bom Jesus de Goiás");
        this.cidades.add("Bonfinópolis");
        this.cidades.add("Bonópolis");
        this.cidades.add("Brazabrantes");
        this.cidades.add("Britânia");
        this.cidades.add("Buriti Alegre");
        this.cidades.add("Buriti de Goiás");
        this.cidades.add("Buritinópolis");
        this.cidades.add("Cabeceiras");
        this.cidades.add("Cachoeira Alta");
        this.cidades.add("Cachoeira de Goiás");
        this.cidades.add("Cachoeira Dourada");
        this.cidades.add("Caçu");
        this.cidades.add("Caiapônia");
        this.cidades.add("Caldas Novas");
        this.cidades.add("Caldazinha");
        this.cidades.add("Campestre de Goiás");
        this.cidades.add("Campinaçu");
        this.cidades.add("Campinorte");
        this.cidades.add("Campo Alegre de Goiás");
        this.cidades.add("Campo Limpo de Goiás");
        this.cidades.add("Campos Belos");
        this.cidades.add("Campos Verdes");
        this.cidades.add("Carmo do Rio Verde");
        this.cidades.add("Castelândia");
        this.cidades.add("Catalão");
        this.cidades.add("Caturaí");
        this.cidades.add("Cavalcante");
        this.cidades.add("Ceres");
        this.cidades.add("Cezarina");
        this.cidades.add("Chapadão do Céu");
        this.cidades.add("Cidade Ocidental");
        this.cidades.add("Cocalzinho de Goiás");
        this.cidades.add("Colinas do Sul");
        this.cidades.add("Córrego do Ouro");
        this.cidades.add("Corumbá de Goiás");
        this.cidades.add("Corumbaíba");
        this.cidades.add("Cristalina");
        this.cidades.add("Cristianópolis");
        this.cidades.add("Crixás");
        this.cidades.add("Cromínia");
        this.cidades.add("Cumari");
        this.cidades.add("Damianópolis");
        this.cidades.add("Damolândia");
        this.cidades.add("Davinópolis");
        this.cidades.add("Diorama");
        this.cidades.add("Doverlândia");
        this.cidades.add("Edealina");
        this.cidades.add("Edéia");
        this.cidades.add("Estrela do Norte");
        this.cidades.add("Faina");
        this.cidades.add("Fazenda Nova");
        this.cidades.add("Firminópolis");
        this.cidades.add("Flores de Goiás");
        this.cidades.add("Formosa");
        this.cidades.add("Formoso");
        this.cidades.add("Gameleira de Goiás");
        this.cidades.add("Divinópolis de Goiás");
        this.cidades.add("Goianápolis");
        this.cidades.add("Goiandira");
        this.cidades.add("Goianésia");
        this.cidades.add("Goiânia");
        this.cidades.add("Goianira");
        this.cidades.add("Goiás");
        this.cidades.add("Goiatuba");
        this.cidades.add("Gouvelândia");
        this.cidades.add("Guapó");
        this.cidades.add("Guaraíta");
        this.cidades.add("Guarani de Goiás");
        this.cidades.add("Guarinos");
        this.cidades.add("Heitoraí");
        this.cidades.add("Hidrolândia");
        this.cidades.add("Hidrolina");
        this.cidades.add("Iaciara");
        this.cidades.add("Inaciolândia");
        this.cidades.add("Indiara");
        this.cidades.add("Inhumas");
        this.cidades.add("Ipameri");
        this.cidades.add("Ipiranga de Goiás");
        this.cidades.add("Iporá");
        this.cidades.add("Israelândia");
        this.cidades.add("Itaberaí");
        this.cidades.add("Itaguari");
        this.cidades.add("Itaguaru");
        this.cidades.add("Itajá");
        this.cidades.add("Itapaci");
        this.cidades.add("Itapirapuã");
        this.cidades.add("Itapuranga");
        this.cidades.add("Itarumã");
        this.cidades.add("Itauçu");
        this.cidades.add("Itumbiara");
        this.cidades.add("Ivolândia");
        this.cidades.add("Jandaia");
        this.cidades.add("Jaraguá");
        this.cidades.add("Jataí");
        this.cidades.add("Jaupaci");
        this.cidades.add("Jesúpolis");
        this.cidades.add("Joviânia");
        this.cidades.add("Jussara");
        this.cidades.add("Lagoa Santa");
        this.cidades.add("Leopoldo de Bulhões");
        this.cidades.add("Luziânia");
        this.cidades.add("Mairipotaba");
        this.cidades.add("Mambaí");
        this.cidades.add("Mara Rosa");
        this.cidades.add("Marzagão");
        this.cidades.add("Matrinchã");
        this.cidades.add("Maurilândia");
        this.cidades.add("Mimoso de Goiás");
        this.cidades.add("Minaçu");
        this.cidades.add("Mineiros");
        this.cidades.add("Moiporá");
        this.cidades.add("Monte Alegre de Goiás");
        this.cidades.add("Montes Claros de Goiás");
        this.cidades.add("Montividiu");
        this.cidades.add("Montividiu do Norte");
        this.cidades.add("Morrinhos");
        this.cidades.add("Morro Agudo de Goiás");
        this.cidades.add("Mossâmedes");
        this.cidades.add("Mozarlândia");
        this.cidades.add("Mundo Novo");
        this.cidades.add("Mutunópolis");
        this.cidades.add("Nazário");
        this.cidades.add("Nerópolis");
        this.cidades.add("Niquelândia");
        this.cidades.add("Nova América");
        this.cidades.add("Nova Aurora");
        this.cidades.add("Nova Crixás");
        this.cidades.add("Nova Glória");
        this.cidades.add("Nova Iguaçu de Goiás");
        this.cidades.add("Nova Roma");
        this.cidades.add("Nova Veneza");
        this.cidades.add("Novo Brasil");
        this.cidades.add("Novo Gama");
        this.cidades.add("Novo Planalto");
        this.cidades.add("Orizona");
        this.cidades.add("Ouro Verde de Goiás");
        this.cidades.add("Ouvidor");
        this.cidades.add("Padre Bernardo");
        this.cidades.add("Palestina de Goiás");
        this.cidades.add("Palmeiras de Goiás");
        this.cidades.add("Palmelo");
        this.cidades.add("Palminópolis");
        this.cidades.add("Panamá");
        this.cidades.add("Paranaiguara");
        this.cidades.add("Paraúna");
        this.cidades.add("Perolândia");
        this.cidades.add("Petrolina de Goiás");
        this.cidades.add("Pilar de Goiás");
        this.cidades.add("Piracanjuba");
        this.cidades.add("Piranhas");
        this.cidades.add("Pirenópolis");
        this.cidades.add("Pires do Rio");
        this.cidades.add("Planaltina");
        this.cidades.add("Pontalina");
        this.cidades.add("Porangatu");
        this.cidades.add("Porteirão");
        this.cidades.add("Portelândia");
        this.cidades.add("Posse");
        this.cidades.add("Professor Jamil");
        this.cidades.add("Quirinópolis");
        this.cidades.add("Rialma");
        this.cidades.add("Rianápolis");
        this.cidades.add("Rio Quente");
        this.cidades.add("Rio Verde");
        this.cidades.add("Rubiataba");
        this.cidades.add("Sanclerlândia");
        this.cidades.add("Santa Bárbara de Goiás");
        this.cidades.add("Santa Cruz de Goiás");
        this.cidades.add("Santa Fé de Goiás");
        this.cidades.add("Santa Helena de Goiás");
        this.cidades.add("Santa Isabel");
        this.cidades.add("Santa Rita do Araguaia");
        this.cidades.add("Santa Rita do Novo Destino");
        this.cidades.add("Santa Rosa de Goiás");
        this.cidades.add("Santa Tereza de Goiás");
        this.cidades.add("Santa Terezinha de Goiás");
        this.cidades.add("Santo Antônio da Barra");
        this.cidades.add("Santo Antônio de Goiás");
        this.cidades.add("Santo Antônio do Descoberto");
        this.cidades.add("São Domingos");
        this.cidades.add("São Francisco de Goiás");
        this.cidades.add("São João D'Aliança");
        this.cidades.add("São João da Paraúna");
        this.cidades.add("São Luís de Montes Belos");
        this.cidades.add("São Luíz do Norte");
        this.cidades.add("São Miguel do Araguaia");
        this.cidades.add("São Miguel do Passa Quatro");
        this.cidades.add("São Patrício");
        this.cidades.add("São Simão");
        this.cidades.add("Senador Canedo");
        this.cidades.add("Serranópolis");
        this.cidades.add("Silvânia");
        this.cidades.add("Simolândia");
        this.cidades.add("Sítio D'Abadia");
        this.cidades.add("Taquaral de Goiás");
        this.cidades.add("Teresina de Goiás");
        this.cidades.add("Terezópolis de Goiás");
        this.cidades.add("Três Ranchos");
        this.cidades.add("Trindade");
        this.cidades.add("Trombas");
        this.cidades.add("Turvânia");
        this.cidades.add("Turvelândia");
        this.cidades.add("Uirapuru");
        this.cidades.add("Uruaçu");
        this.cidades.add("Uruana");
        this.cidades.add("Urutaí");
        this.cidades.add("Valparaíso de Goiás");
        this.cidades.add("Varjão");
        this.cidades.add("Vianópolis");
        this.cidades.add("Vicentinópolis");
        this.cidades.add("Vila Boa");
        this.cidades.add("Vila Propício");

        return cidades;
    }
}