package com.igor.listviewclick.EstadosCidades;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Igor on 18/03/2018.
 */

public class MA {

    List<String> cidades = new ArrayList<>();

    public MA() {}

    public List<String> getCidades() {

        this.cidades.add("Açailândia");
        this.cidades.add("Afonso Cunha");
        this.cidades.add("Água Doce do Maranhão");
        this.cidades.add("Alcântara");
        this.cidades.add("Aldeias Altas");
        this.cidades.add("Altamira do Maranhão");
        this.cidades.add("Alto Alegre do Maranhão");
        this.cidades.add("Alto Alegre do Pindaré");
        this.cidades.add("Alto Parnaíba");
        this.cidades.add("Amapá do Maranhão");
        this.cidades.add("Amarante do Maranhão");
        this.cidades.add("Anajatuba");
        this.cidades.add("Anapurus");
        this.cidades.add("Apicum-Açu");
        this.cidades.add("Araguanã");
        this.cidades.add("Araioses");
        this.cidades.add("Arame");
        this.cidades.add("Arari");
        this.cidades.add("Axixá");
        this.cidades.add("Bacabal");
        this.cidades.add("Bacabeira");
        this.cidades.add("Bacuri");
        this.cidades.add("Bacurituba");
        this.cidades.add("Balsas");
        this.cidades.add("Barão de Grajaú");
        this.cidades.add("Barra do Corda");
        this.cidades.add("Barreirinhas");
        this.cidades.add("Belágua");
        this.cidades.add("Bela Vista do Maranhão");
        this.cidades.add("Benedito Leite");
        this.cidades.add("Bequimão");
        this.cidades.add("Bernardo do Mearim");
        this.cidades.add("Boa Vista do Gurupi");
        this.cidades.add("Bom Jardim");
        this.cidades.add("Bom Jesus das Selvas");
        this.cidades.add("Bom Lugar");
        this.cidades.add("Brejo");
        this.cidades.add("Brejo de Areia");
        this.cidades.add("Buriti");
        this.cidades.add("Buriti Bravo");
        this.cidades.add("Buriticupu");
        this.cidades.add("Buritirana");
        this.cidades.add("Cachoeira Grande");
        this.cidades.add("Cajapió");
        this.cidades.add("Cajari");
        this.cidades.add("Campestre do Maranhão");
        this.cidades.add("Cândido Mendes");
        this.cidades.add("Cantanhede");
        this.cidades.add("Capinzal do Norte");
        this.cidades.add("Carolina");
        this.cidades.add("Carutapera");
        this.cidades.add("Caxias");
        this.cidades.add("Cedral");
        this.cidades.add("Central do Maranhão");
        this.cidades.add("Centro do Guilherme");
        this.cidades.add("Centro Novo do Maranhão");
        this.cidades.add("Chapadinha");
        this.cidades.add("Cidelândia");
        this.cidades.add("Codó");
        this.cidades.add("Coelho Neto");
        this.cidades.add("Colinas");
        this.cidades.add("Conceição do Lago-Açu");
        this.cidades.add("Coroatá");
        this.cidades.add("Cururupu");
        this.cidades.add("Davinópolis");
        this.cidades.add("Dom Pedro");
        this.cidades.add("Duque Bacelar");
        this.cidades.add("Esperantinópolis");
        this.cidades.add("Estreito");
        this.cidades.add("Feira Nova do Maranhão");
        this.cidades.add("Fernando Falcão");
        this.cidades.add("Formosa da Serra Negra");
        this.cidades.add("Fortaleza dos Nogueiras");
        this.cidades.add("Fortuna");
        this.cidades.add("Godofredo Viana");
        this.cidades.add("Gonçalves Dias");
        this.cidades.add("Governador Archer");
        this.cidades.add("Governador Edison Lobão");
        this.cidades.add("Governador Eugênio Barros");
        this.cidades.add("Governador Luiz Rocha");
        this.cidades.add("Governador Newton Bello");
        this.cidades.add("Governador Nunes Freire");
        this.cidades.add("Graça Aranha");
        this.cidades.add("Grajaú");
        this.cidades.add("Guimarães");
        this.cidades.add("Humberto de Campos");
        this.cidades.add("Icatu");
        this.cidades.add("Igarapé do Meio");
        this.cidades.add("Igarapé Grande");
        this.cidades.add("Imperatriz");
        this.cidades.add("Itaipava do Grajaú");
        this.cidades.add("Itapecuru Mirim");
        this.cidades.add("Itinga do Maranhão");
        this.cidades.add("Jatobá");
        this.cidades.add("Jenipapo dos Vieiras");
        this.cidades.add("João Lisboa");
        this.cidades.add("Joselândia");
        this.cidades.add("Junco do Maranhão");
        this.cidades.add("Lago da Pedra");
        this.cidades.add("Lago do Junco");
        this.cidades.add("Lago Verde");
        this.cidades.add("Lagoa do Mato");
        this.cidades.add("Lago dos Rodrigues");
        this.cidades.add("Lagoa Grande do Maranhão");
        this.cidades.add("Lajeado Novo");
        this.cidades.add("Lima Campos");
        this.cidades.add("Loreto");
        this.cidades.add("Luís Domingues");
        this.cidades.add("Magalhães de Almeida");
        this.cidades.add("Maracaçumé");
        this.cidades.add("Marajá do Sena");
        this.cidades.add("Maranhãozinho");
        this.cidades.add("Mata Roma");
        this.cidades.add("Matinha");
        this.cidades.add("Matões");
        this.cidades.add("Matões do Norte");
        this.cidades.add("Milagres do Maranhão");
        this.cidades.add("Mirador");
        this.cidades.add("Miranda do Norte");
        this.cidades.add("Mirinzal");
        this.cidades.add("Monção");
        this.cidades.add("Montes Altos");
        this.cidades.add("Morros");
        this.cidades.add("Nina Rodrigues");
        this.cidades.add("Nova Colinas");
        this.cidades.add("Nova Iorque");
        this.cidades.add("Nova Olinda do Maranhão");
        this.cidades.add("Olho D'Água das Cunhãs");
        this.cidades.add("Olinda Nova do Maranhão");
        this.cidades.add("Paço do Lumiar");
        this.cidades.add("Palmeirândia");
        this.cidades.add("Paraibano");
        this.cidades.add("Parnarama");
        this.cidades.add("Passagem Franca");
        this.cidades.add("Pastos Bons");
        this.cidades.add("Paulino Neves");
        this.cidades.add("Paulo Ramos");
        this.cidades.add("Pedreiras");
        this.cidades.add("Pedro do Rosário");
        this.cidades.add("Penalva");
        this.cidades.add("Peri Mirim");
        this.cidades.add("Peritoró");
        this.cidades.add("Pindaré-Mirim");
        this.cidades.add("Pinheiro");
        this.cidades.add("Pio XII");
        this.cidades.add("Pirapemas");
        this.cidades.add("Poção de Pedras");
        this.cidades.add("Porto Franco");
        this.cidades.add("Porto Rico do Maranhão");
        this.cidades.add("Presidente Dutra");
        this.cidades.add("Presidente Juscelino");
        this.cidades.add("Presidente Médici");
        this.cidades.add("Presidente Sarney");
        this.cidades.add("Presidente Vargas");
        this.cidades.add("Primeira Cruz");
        this.cidades.add("Raposa");
        this.cidades.add("Riachão");
        this.cidades.add("Ribamar Fiquene");
        this.cidades.add("Rosário");
        this.cidades.add("Sambaíba");
        this.cidades.add("Santa Filomena do Maranhão");
        this.cidades.add("Santa Helena");
        this.cidades.add("Santa Inês");
        this.cidades.add("Santa Luzia");
        this.cidades.add("Santa Luzia do Paruá");
        this.cidades.add("Santa Quitéria do Maranhão");
        this.cidades.add("Santa Rita");
        this.cidades.add("Santana do Maranhão");
        this.cidades.add("Santo Amaro do Maranhão");
        this.cidades.add("Santo Antônio dos Lopes");
        this.cidades.add("São Benedito do Rio Preto");
        this.cidades.add("São Bento");
        this.cidades.add("São Bernardo");
        this.cidades.add("São Domingos do Azeitão");
        this.cidades.add("São Domingos do Maranhão");
        this.cidades.add("São Félix de Balsas");
        this.cidades.add("São Francisco do Brejão");
        this.cidades.add("São Francisco do Maranhão");
        this.cidades.add("São João Batista");
        this.cidades.add("São João do Carú");
        this.cidades.add("São João do Paraíso");
        this.cidades.add("São João do Soter");
        this.cidades.add("São João dos Patos");
        this.cidades.add("São José de Ribamar");
        this.cidades.add("São José dos Basílios");
        this.cidades.add("São Luís");
        this.cidades.add("São Luís Gonzaga do Maranhão");
        this.cidades.add("São Mateus do Maranhão");
        this.cidades.add("São Pedro da Água Branca");
        this.cidades.add("São Pedro dos Crentes");
        this.cidades.add("São Raimundo das Mangabeiras");
        this.cidades.add("São Raimundo do Doca Bezerra");
        this.cidades.add("São Roberto");
        this.cidades.add("São Vicente Ferrer");
        this.cidades.add("Satubinha");
        this.cidades.add("Senador Alexandre Costa");
        this.cidades.add("Senador La Rocque");
        this.cidades.add("Serrano do Maranhão");
        this.cidades.add("Sítio Novo");
        this.cidades.add("Sucupira do Norte");
        this.cidades.add("Sucupira do Riachão");
        this.cidades.add("Tasso Fragoso");
        this.cidades.add("Timbiras");
        this.cidades.add("Timon");
        this.cidades.add("Trizidela do Vale");
        this.cidades.add("Tufilândia");
        this.cidades.add("Tuntum");
        this.cidades.add("Turiaçu");
        this.cidades.add("Turilândia");
        this.cidades.add("Tutóia");
        this.cidades.add("Urbano Santos");
        this.cidades.add("Vargem Grande");
        this.cidades.add("Viana");
        this.cidades.add("Vila Nova dos Martírios");
        this.cidades.add("Vitória do Mearim");
        this.cidades.add("Vitorino Freire");
        this.cidades.add("Zé Doca");
        this.cidades.add("Açailândia");
        this.cidades.add("Afonso Cunha");
        this.cidades.add("Água Doce do Maranhão");
        this.cidades.add("Alcântara");
        this.cidades.add("Aldeias Altas");
        this.cidades.add("Altamira do Maranhão");
        this.cidades.add("Alto Alegre do Maranhão");
        this.cidades.add("Alto Alegre do Pindaré");
        this.cidades.add("Alto Parnaíba");
        this.cidades.add("Amapá do Maranhão");
        this.cidades.add("Amarante do Maranhão");
        this.cidades.add("Anajatuba");
        this.cidades.add("Anapurus");
        this.cidades.add("Apicum-Açu");
        this.cidades.add("Araguanã");
        this.cidades.add("Araioses");
        this.cidades.add("Arame");
        this.cidades.add("Arari");
        this.cidades.add("Axixá");
        this.cidades.add("Bacabal");
        this.cidades.add("Bacabeira");
        this.cidades.add("Bacuri");
        this.cidades.add("Bacurituba");
        this.cidades.add("Balsas");
        this.cidades.add("Barão de Grajaú");
        this.cidades.add("Barra do Corda");
        this.cidades.add("Barreirinhas");
        this.cidades.add("Belágua");
        this.cidades.add("Bela Vista do Maranhão");
        this.cidades.add("Benedito Leite");
        this.cidades.add("Bequimão");
        this.cidades.add("Bernardo do Mearim");
        this.cidades.add("Boa Vista do Gurupi");
        this.cidades.add("Bom Jardim");
        this.cidades.add("Bom Jesus das Selvas");
        this.cidades.add("Bom Lugar");
        this.cidades.add("Brejo");
        this.cidades.add("Brejo de Areia");
        this.cidades.add("Buriti");
        this.cidades.add("Buriti Bravo");
        this.cidades.add("Buriticupu");
        this.cidades.add("Buritirana");
        this.cidades.add("Cachoeira Grande");
        this.cidades.add("Cajapió");
        this.cidades.add("Cajari");
        this.cidades.add("Campestre do Maranhão");
        this.cidades.add("Cândido Mendes");
        this.cidades.add("Cantanhede");
        this.cidades.add("Capinzal do Norte");
        this.cidades.add("Carolina");
        this.cidades.add("Carutapera");
        this.cidades.add("Caxias");
        this.cidades.add("Cedral");
        this.cidades.add("Central do Maranhão");
        this.cidades.add("Centro do Guilherme");
        this.cidades.add("Centro Novo do Maranhão");
        this.cidades.add("Chapadinha");
        this.cidades.add("Cidelândia");
        this.cidades.add("Codó");
        this.cidades.add("Coelho Neto");
        this.cidades.add("Colinas");
        this.cidades.add("Conceição do Lago-Açu");
        this.cidades.add("Coroatá");
        this.cidades.add("Cururupu");
        this.cidades.add("Davinópolis");
        this.cidades.add("Dom Pedro");
        this.cidades.add("Duque Bacelar");
        this.cidades.add("Esperantinópolis");
        this.cidades.add("Estreito");
        this.cidades.add("Feira Nova do Maranhão");
        this.cidades.add("Fernando Falcão");
        this.cidades.add("Formosa da Serra Negra");
        this.cidades.add("Fortaleza dos Nogueiras");
        this.cidades.add("Fortuna");
        this.cidades.add("Godofredo Viana");
        this.cidades.add("Gonçalves Dias");
        this.cidades.add("Governador Archer");
        this.cidades.add("Governador Edison Lobão");
        this.cidades.add("Governador Eugênio Barros");
        this.cidades.add("Governador Luiz Rocha");
        this.cidades.add("Governador Newton Bello");
        this.cidades.add("Governador Nunes Freire");
        this.cidades.add("Graça Aranha");
        this.cidades.add("Grajaú");
        this.cidades.add("Guimarães");
        this.cidades.add("Humberto de Campos");
        this.cidades.add("Icatu");
        this.cidades.add("Igarapé do Meio");
        this.cidades.add("Igarapé Grande");
        this.cidades.add("Imperatriz");
        this.cidades.add("Itaipava do Grajaú");
        this.cidades.add("Itapecuru Mirim");
        this.cidades.add("Itinga do Maranhão");
        this.cidades.add("Jatobá");
        this.cidades.add("Jenipapo dos Vieiras");
        this.cidades.add("João Lisboa");
        this.cidades.add("Joselândia");
        this.cidades.add("Junco do Maranhão");
        this.cidades.add("Lago da Pedra");
        this.cidades.add("Lago do Junco");
        this.cidades.add("Lago Verde");
        this.cidades.add("Lagoa do Mato");
        this.cidades.add("Lago dos Rodrigues");
        this.cidades.add("Lagoa Grande do Maranhão");
        this.cidades.add("Lajeado Novo");
        this.cidades.add("Lima Campos");
        this.cidades.add("Loreto");
        this.cidades.add("Luís Domingues");
        this.cidades.add("Magalhães de Almeida");
        this.cidades.add("Maracaçumé");
        this.cidades.add("Marajá do Sena");
        this.cidades.add("Maranhãozinho");
        this.cidades.add("Mata Roma");
        this.cidades.add("Matinha");
        this.cidades.add("Matões");
        this.cidades.add("Matões do Norte");
        this.cidades.add("Milagres do Maranhão");
        this.cidades.add("Mirador");
        this.cidades.add("Miranda do Norte");
        this.cidades.add("Mirinzal");
        this.cidades.add("Monção");
        this.cidades.add("Montes Altos");
        this.cidades.add("Morros");
        this.cidades.add("Nina Rodrigues");
        this.cidades.add("Nova Colinas");
        this.cidades.add("Nova Iorque");
        this.cidades.add("Nova Olinda do Maranhão");
        this.cidades.add("Olho D'Água das Cunhãs");
        this.cidades.add("Olinda Nova do Maranhão");
        this.cidades.add("Paço do Lumiar");
        this.cidades.add("Palmeirândia");
        this.cidades.add("Paraibano");
        this.cidades.add("Parnarama");
        this.cidades.add("Passagem Franca");
        this.cidades.add("Pastos Bons");
        this.cidades.add("Paulino Neves");
        this.cidades.add("Paulo Ramos");
        this.cidades.add("Pedreiras");
        this.cidades.add("Pedro do Rosário");
        this.cidades.add("Penalva");
        this.cidades.add("Peri Mirim");
        this.cidades.add("Peritoró");
        this.cidades.add("Pindaré-Mirim");
        this.cidades.add("Pinheiro");
        this.cidades.add("Pio XII");
        this.cidades.add("Pirapemas");
        this.cidades.add("Poção de Pedras");
        this.cidades.add("Porto Franco");
        this.cidades.add("Porto Rico do Maranhão");
        this.cidades.add("Presidente Dutra");
        this.cidades.add("Presidente Juscelino");
        this.cidades.add("Presidente Médici");
        this.cidades.add("Presidente Sarney");
        this.cidades.add("Presidente Vargas");
        this.cidades.add("Primeira Cruz");
        this.cidades.add("Raposa");
        this.cidades.add("Riachão");
        this.cidades.add("Ribamar Fiquene");
        this.cidades.add("Rosário");
        this.cidades.add("Sambaíba");
        this.cidades.add("Santa Filomena do Maranhão");
        this.cidades.add("Santa Helena");
        this.cidades.add("Santa Inês");
        this.cidades.add("Santa Luzia");
        this.cidades.add("Santa Luzia do Paruá");
        this.cidades.add("Santa Quitéria do Maranhão");
        this.cidades.add("Santa Rita");
        this.cidades.add("Santana do Maranhão");
        this.cidades.add("Santo Amaro do Maranhão");
        this.cidades.add("Santo Antônio dos Lopes");
        this.cidades.add("São Benedito do Rio Preto");
        this.cidades.add("São Bento");
        this.cidades.add("São Bernardo");
        this.cidades.add("São Domingos do Azeitão");
        this.cidades.add("São Domingos do Maranhão");
        this.cidades.add("São Félix de Balsas");
        this.cidades.add("São Francisco do Brejão");
        this.cidades.add("São Francisco do Maranhão");
        this.cidades.add("São João Batista");
        this.cidades.add("São João do Carú");
        this.cidades.add("São João do Paraíso");
        this.cidades.add("São João do Soter");
        this.cidades.add("São João dos Patos");
        this.cidades.add("São José de Ribamar");
        this.cidades.add("São José dos Basílios");
        this.cidades.add("São Luís");
        this.cidades.add("São Luís Gonzaga do Maranhão");
        this.cidades.add("São Mateus do Maranhão");
        this.cidades.add("São Pedro da Água Branca");
        this.cidades.add("São Pedro dos Crentes");
        this.cidades.add("São Raimundo das Mangabeiras");
        this.cidades.add("São Raimundo do Doca Bezerra");
        this.cidades.add("São Roberto");
        this.cidades.add("São Vicente Ferrer");
        this.cidades.add("Satubinha");
        this.cidades.add("Senador Alexandre Costa");
        this.cidades.add("Senador La Rocque");
        this.cidades.add("Serrano do Maranhão");
        this.cidades.add("Sítio Novo");
        this.cidades.add("Sucupira do Norte");
        this.cidades.add("Sucupira do Riachão");
        this.cidades.add("Tasso Fragoso");
        this.cidades.add("Timbiras");
        this.cidades.add("Timon");
        this.cidades.add("Trizidela do Vale");
        this.cidades.add("Tufilândia");
        this.cidades.add("Tuntum");
        this.cidades.add("Turiaçu");
        this.cidades.add("Turilândia");
        this.cidades.add("Tutóia");
        this.cidades.add("Urbano Santos");
        this.cidades.add("Vargem Grande");
        this.cidades.add("Viana");
        this.cidades.add("Vila Nova dos Martírios");
        this.cidades.add("Vitória do Mearim");
        this.cidades.add("Vitorino Freire");
        this.cidades.add("Zé Doca");

        return cidades;
    }
}