package com.igor.listviewclick.EstadosCidades;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Igor on 18/03/2018.
 */

public class MG {

    List<String> cidades = new ArrayList<>();

    public MG() {}

    public List<String> getCidades() {

        this.cidades.add("Abadia dos Dourados");
        this.cidades.add("Abaeté");
        this.cidades.add("Abre Campo");
        this.cidades.add("Acaiaca");
        this.cidades.add("Açucena");
        this.cidades.add("Água Boa");
        this.cidades.add("Água Comprida");
        this.cidades.add("Aguanil");
        this.cidades.add("Águas Formosas");
        this.cidades.add("Águas Vermelhas");
        this.cidades.add("Aimorés");
        this.cidades.add("Aiuruoca");
        this.cidades.add("Alagoa");
        this.cidades.add("Albertina");
        this.cidades.add("Além Paraíba");
        this.cidades.add("Alfenas");
        this.cidades.add("Alfredo Vasconcelos");
        this.cidades.add("Almenara");
        this.cidades.add("Alpercata");
        this.cidades.add("Alpinópolis");
        this.cidades.add("Alterosa");
        this.cidades.add("Alto Caparaó");
        this.cidades.add("Alto Rio Doce");
        this.cidades.add("Alvarenga");
        this.cidades.add("Alvinópolis");
        this.cidades.add("Alvorada de Minas");
        this.cidades.add("Amparo do Serra");
        this.cidades.add("Andradas");
        this.cidades.add("Cachoeira de Pajeú");
        this.cidades.add("Andrelândia");
        this.cidades.add("Angelândia");
        this.cidades.add("Antônio Carlos");
        this.cidades.add("Antônio Dias");
        this.cidades.add("Antônio Prado de Minas");
        this.cidades.add("Araçaí");
        this.cidades.add("Aracitaba");
        this.cidades.add("Araçuaí");
        this.cidades.add("Araguari");
        this.cidades.add("Arantina");
        this.cidades.add("Araponga");
        this.cidades.add("Araporã");
        this.cidades.add("Arapuá");
        this.cidades.add("Araújos");
        this.cidades.add("Araxá");
        this.cidades.add("Arceburgo");
        this.cidades.add("Arcos");
        this.cidades.add("Areado");
        this.cidades.add("Argirita");
        this.cidades.add("Aricanduva");
        this.cidades.add("Arinos");
        this.cidades.add("Astolfo Dutra");
        this.cidades.add("Ataléia");
        this.cidades.add("Augusto de Lima");
        this.cidades.add("Baependi");
        this.cidades.add("Baldim");
        this.cidades.add("Bambuí");
        this.cidades.add("Bandeira");
        this.cidades.add("Bandeira do Sul");
        this.cidades.add("Barão de Cocais");
        this.cidades.add("Barão de Monte Alto");
        this.cidades.add("Barbacena");
        this.cidades.add("Barra Longa");
        this.cidades.add("Barroso");
        this.cidades.add("Bela Vista de Minas");
        this.cidades.add("Belmiro Braga");
        this.cidades.add("Belo Horizonte");
        this.cidades.add("Belo Oriente");
        this.cidades.add("Belo Vale");
        this.cidades.add("Berilo");
        this.cidades.add("Bertópolis");
        this.cidades.add("Berizal");
        this.cidades.add("Betim");
        this.cidades.add("Bias Fortes");
        this.cidades.add("Bicas");
        this.cidades.add("Biquinhas");
        this.cidades.add("Boa Esperança");
        this.cidades.add("Bocaina de Minas");
        this.cidades.add("Bocaiúva");
        this.cidades.add("Bom Despacho");
        this.cidades.add("Bom Jardim de Minas");
        this.cidades.add("Bom Jesus da Penha");
        this.cidades.add("Bom Jesus do Amparo");
        this.cidades.add("Bom Jesus do Galho");
        this.cidades.add("Bom Repouso");
        this.cidades.add("Bom Sucesso");
        this.cidades.add("Bonfim");
        this.cidades.add("Bonfinópolis de Minas");
        this.cidades.add("Bonito de Minas");
        this.cidades.add("Borda da Mata");
        this.cidades.add("Botelhos");
        this.cidades.add("Botumirim");
        this.cidades.add("Brasilândia de Minas");
        this.cidades.add("Brasília de Minas");
        this.cidades.add("Brás Pires");
        this.cidades.add("Braúnas");
        this.cidades.add("Brazópolis");
        this.cidades.add("Brumadinho");
        this.cidades.add("Bueno Brandão");
        this.cidades.add("Buenópolis");
        this.cidades.add("Bugre");
        this.cidades.add("Buritis");
        this.cidades.add("Buritizeiro");
        this.cidades.add("Cabeceira Grande");
        this.cidades.add("Cabo Verde");
        this.cidades.add("Cachoeira da Prata");
        this.cidades.add("Cachoeira de Minas");
        this.cidades.add("Cachoeira Dourada");
        this.cidades.add("Caetanópolis");
        this.cidades.add("Caeté");
        this.cidades.add("Caiana");
        this.cidades.add("Cajuri");
        this.cidades.add("Caldas");
        this.cidades.add("Camacho");
        this.cidades.add("Camanducaia");
        this.cidades.add("Cambuí");
        this.cidades.add("Cambuquira");
        this.cidades.add("Campanário");
        this.cidades.add("Campanha");
        this.cidades.add("Campestre");
        this.cidades.add("Campina Verde");
        this.cidades.add("Campo Azul");
        this.cidades.add("Campo Belo");
        this.cidades.add("Campo do Meio");
        this.cidades.add("Campo Florido");
        this.cidades.add("Campos Altos");
        this.cidades.add("Campos Gerais");
        this.cidades.add("Canaã");
        this.cidades.add("Canápolis");
        this.cidades.add("Cana Verde");
        this.cidades.add("Candeias");
        this.cidades.add("Cantagalo");
        this.cidades.add("Caparaó");
        this.cidades.add("Capela Nova");
        this.cidades.add("Capelinha");
        this.cidades.add("Capetinga");
        this.cidades.add("Capim Branco");
        this.cidades.add("Capinópolis");
        this.cidades.add("Capitão Andrade");
        this.cidades.add("Capitão Enéas");
        this.cidades.add("Capitólio");
        this.cidades.add("Caputira");
        this.cidades.add("Caraí");
        this.cidades.add("Caranaíba");
        this.cidades.add("Carandaí");
        this.cidades.add("Carangola");
        this.cidades.add("Caratinga");
        this.cidades.add("Carbonita");
        this.cidades.add("Careaçu");
        this.cidades.add("Carlos Chagas");
        this.cidades.add("Carmésia");
        this.cidades.add("Carmo da Cachoeira");
        this.cidades.add("Carmo da Mata");
        this.cidades.add("Carmo de Minas");
        this.cidades.add("Carmo do Cajuru");
        this.cidades.add("Carmo do Paranaíba");
        this.cidades.add("Carmo do Rio Claro");
        this.cidades.add("Carmópolis de Minas");
        this.cidades.add("Carneirinho");
        this.cidades.add("Carrancas");
        this.cidades.add("Carvalhópolis");
        this.cidades.add("Carvalhos");
        this.cidades.add("Casa Grande");
        this.cidades.add("Cascalho Rico");
        this.cidades.add("Cássia");
        this.cidades.add("Conceição da Barra de Minas");
        this.cidades.add("Cataguases");
        this.cidades.add("Catas Altas");
        this.cidades.add("Catas Altas da Noruega");
        this.cidades.add("Catuji");
        this.cidades.add("Catuti");
        this.cidades.add("Caxambu");
        this.cidades.add("Cedro do Abaeté");
        this.cidades.add("Central de Minas");
        this.cidades.add("Centralina");
        this.cidades.add("Chácara");
        this.cidades.add("Chalé");
        this.cidades.add("Chapada do Norte");
        this.cidades.add("Chapada Gaúcha");
        this.cidades.add("Chiador");
        this.cidades.add("Cipotânea");
        this.cidades.add("Claraval");
        this.cidades.add("Claro dos Poções");
        this.cidades.add("Cláudio");
        this.cidades.add("Coimbra");
        this.cidades.add("Coluna");
        this.cidades.add("Comendador Gomes");
        this.cidades.add("Comercinho");
        this.cidades.add("Conceição da Aparecida");
        this.cidades.add("Conceição das Pedras");
        this.cidades.add("Conceição das Alagoas");
        this.cidades.add("Conceição de Ipanema");
        this.cidades.add("Conceição do Mato Dentro");
        this.cidades.add("Conceição do Pará");
        this.cidades.add("Conceição do Rio Verde");
        this.cidades.add("Conceição dos Ouros");
        this.cidades.add("Cônego Marinho");
        this.cidades.add("Confins");
        this.cidades.add("Congonhal");
        this.cidades.add("Congonhas");
        this.cidades.add("Congonhas do Norte");
        this.cidades.add("Conquista");
        this.cidades.add("Conselheiro Lafaiete");
        this.cidades.add("Conselheiro Pena");
        this.cidades.add("Consolação");
        this.cidades.add("Contagem");
        this.cidades.add("Coqueiral");
        this.cidades.add("Coração de Jesus");
        this.cidades.add("Cordisburgo");
        this.cidades.add("Cordislândia");
        this.cidades.add("Corinto");
        this.cidades.add("Coroaci");
        this.cidades.add("Coromandel");
        this.cidades.add("Coronel Fabriciano");
        this.cidades.add("Coronel Murta");
        this.cidades.add("Coronel Pacheco");
        this.cidades.add("Coronel Xavier Chaves");
        this.cidades.add("Córrego Danta");
        this.cidades.add("Córrego do Bom Jesus");
        this.cidades.add("Córrego Fundo");
        this.cidades.add("Córrego Novo");
        this.cidades.add("Couto de Magalhães de Minas");
        this.cidades.add("Crisólita");
        this.cidades.add("Cristais");
        this.cidades.add("Cristália");
        this.cidades.add("Cristiano Otoni");
        this.cidades.add("Cristina");
        this.cidades.add("Crucilândia");
        this.cidades.add("Cruzeiro da Fortaleza");
        this.cidades.add("Cruzília");
        this.cidades.add("Cuparaque");
        this.cidades.add("Curral de Dentro");
        this.cidades.add("Curvelo");
        this.cidades.add("Datas");
        this.cidades.add("Delfim Moreira");
        this.cidades.add("Delfinópolis");
        this.cidades.add("Delta");
        this.cidades.add("Descoberto");
        this.cidades.add("Desterro de Entre Rios");
        this.cidades.add("Desterro do Melo");
        this.cidades.add("Diamantina");
        this.cidades.add("Diogo de Vasconcelos");
        this.cidades.add("Dionísio");
        this.cidades.add("Divinésia");
        this.cidades.add("Divino");
        this.cidades.add("Divino das Laranjeiras");
        this.cidades.add("Divinolândia de Minas");
        this.cidades.add("Divinópolis");
        this.cidades.add("Divisa Alegre");
        this.cidades.add("Divisa Nova");
        this.cidades.add("Divisópolis");
        this.cidades.add("Dom Bosco");
        this.cidades.add("Dom Cavati");
        this.cidades.add("Dom Joaquim");
        this.cidades.add("Dom Silvério");
        this.cidades.add("Dom Viçoso");
        this.cidades.add("Dona Eusébia");
        this.cidades.add("Dores de Campos");
        this.cidades.add("Dores de Guanhães");
        this.cidades.add("Dores do Indaiá");
        this.cidades.add("Dores do Turvo");
        this.cidades.add("Doresópolis");
        this.cidades.add("Douradoquara");
        this.cidades.add("Durandé");
        this.cidades.add("Elói Mendes");
        this.cidades.add("Engenheiro Caldas");
        this.cidades.add("Engenheiro Navarro");
        this.cidades.add("Entre Folhas");
        this.cidades.add("Entre Rios de Minas");
        this.cidades.add("Ervália");
        this.cidades.add("Esmeraldas");
        this.cidades.add("Espera Feliz");
        this.cidades.add("Espinosa");
        this.cidades.add("Espírito Santo do Dourado");
        this.cidades.add("Estiva");
        this.cidades.add("Estrela Dalva");
        this.cidades.add("Estrela do Indaiá");
        this.cidades.add("Estrela do Sul");
        this.cidades.add("Eugenópolis");
        this.cidades.add("Ewbank da Câmara");
        this.cidades.add("Extrema");
        this.cidades.add("Fama");
        this.cidades.add("Faria Lemos");
        this.cidades.add("Felício dos Santos");
        this.cidades.add("São Gonçalo do Rio Preto");
        this.cidades.add("Felisburgo");
        this.cidades.add("Felixlândia");
        this.cidades.add("Fernandes Tourinho");
        this.cidades.add("Ferros");
        this.cidades.add("Fervedouro");
        this.cidades.add("Florestal");
        this.cidades.add("Formiga");
        this.cidades.add("Formoso");
        this.cidades.add("Fortaleza de Minas");
        this.cidades.add("Fortuna de Minas");
        this.cidades.add("Francisco Badaró");
        this.cidades.add("Francisco Dumont");
        this.cidades.add("Francisco Sá");
        this.cidades.add("Franciscópolis");
        this.cidades.add("Frei Gaspar");
        this.cidades.add("Frei Inocêncio");
        this.cidades.add("Frei Lagonegro");
        this.cidades.add("Fronteira");
        this.cidades.add("Fronteira dos Vales");
        this.cidades.add("Fruta de Leite");
        this.cidades.add("Frutal");
        this.cidades.add("Funilândia");
        this.cidades.add("Galiléia");
        this.cidades.add("Gameleiras");
        this.cidades.add("Glaucilândia");
        this.cidades.add("Goiabeira");
        this.cidades.add("Goianá");
        this.cidades.add("Gonçalves");
        this.cidades.add("Gonzaga");
        this.cidades.add("Gouveia");
        this.cidades.add("Governador Valadares");
        this.cidades.add("Grão Mogol");
        this.cidades.add("Grupiara");
        this.cidades.add("Guanhães");
        this.cidades.add("Guapé");
        this.cidades.add("Guaraciaba");
        this.cidades.add("Guaraciama");
        this.cidades.add("Guaranésia");
        this.cidades.add("Guarani");
        this.cidades.add("Guarará");
        this.cidades.add("Guarda-Mor");
        this.cidades.add("Guaxupé");
        this.cidades.add("Guidoval");
        this.cidades.add("Guimarânia");
        this.cidades.add("Guiricema");
        this.cidades.add("Gurinhatã");
        this.cidades.add("Heliodora");
        this.cidades.add("Iapu");
        this.cidades.add("Ibertioga");
        this.cidades.add("Ibiá");
        this.cidades.add("Ibiaí");
        this.cidades.add("Ibiracatu");
        this.cidades.add("Ibiraci");
        this.cidades.add("Ibirité");
        this.cidades.add("Ibitiúra de Minas");
        this.cidades.add("Ibituruna");
        this.cidades.add("Icaraí de Minas");
        this.cidades.add("Igarapé");
        this.cidades.add("Igaratinga");
        this.cidades.add("Iguatama");
        this.cidades.add("Ijaci");
        this.cidades.add("Ilicínea");
        this.cidades.add("Imbé de Minas");
        this.cidades.add("Inconfidentes");
        this.cidades.add("Indaiabira");
        this.cidades.add("Indianópolis");
        this.cidades.add("Ingaí");
        this.cidades.add("Inhapim");
        this.cidades.add("Inhaúma");
        this.cidades.add("Inimutaba");
        this.cidades.add("Ipaba");
        this.cidades.add("Ipanema");
        this.cidades.add("Ipatinga");
        this.cidades.add("Ipiaçu");
        this.cidades.add("Ipuiúna");
        this.cidades.add("Iraí de Minas");
        this.cidades.add("Itabira");
        this.cidades.add("Itabirinha");
        this.cidades.add("Itabirito");
        this.cidades.add("Itacambira");
        this.cidades.add("Itacarambi");
        this.cidades.add("Itaguara");
        this.cidades.add("Itaipé");
        this.cidades.add("Itajubá");
        this.cidades.add("Itamarandiba");
        this.cidades.add("Itamarati de Minas");
        this.cidades.add("Itambacuri");
        this.cidades.add("Itambé do Mato Dentro");
        this.cidades.add("Itamogi");
        this.cidades.add("Itamonte");
        this.cidades.add("Itanhandu");
        this.cidades.add("Itanhomi");
        this.cidades.add("Itaobim");
        this.cidades.add("Itapagipe");
        this.cidades.add("Itapecerica");
        this.cidades.add("Itapeva");
        this.cidades.add("Itatiaiuçu");
        this.cidades.add("Itaú de Minas");
        this.cidades.add("Itaúna");
        this.cidades.add("Itaverava");
        this.cidades.add("Itinga");
        this.cidades.add("Itueta");
        this.cidades.add("Ituiutaba");
        this.cidades.add("Itumirim");
        this.cidades.add("Iturama");
        this.cidades.add("Itutinga");
        this.cidades.add("Jaboticatubas");
        this.cidades.add("Jacinto");
        this.cidades.add("Jacuí");
        this.cidades.add("Jacutinga");
        this.cidades.add("Jaguaraçu");
        this.cidades.add("Jaíba");
        this.cidades.add("Jampruca");
        this.cidades.add("Janaúba");
        this.cidades.add("Januária");
        this.cidades.add("Japaraíba");
        this.cidades.add("Japonvar");
        this.cidades.add("Jeceaba");
        this.cidades.add("Jenipapo de Minas");
        this.cidades.add("Jequeri");
        this.cidades.add("Jequitaí");
        this.cidades.add("Jequitibá");
        this.cidades.add("Jequitinhonha");
        this.cidades.add("Jesuânia");
        this.cidades.add("Joaíma");
        this.cidades.add("Joanésia");
        this.cidades.add("João Monlevade");
        this.cidades.add("João Pinheiro");
        this.cidades.add("Joaquim Felício");
        this.cidades.add("Jordânia");
        this.cidades.add("José Gonçalves de Minas");
        this.cidades.add("José Raydan");
        this.cidades.add("Josenópolis");
        this.cidades.add("Nova União");
        this.cidades.add("Juatuba");
        this.cidades.add("Juiz de Fora");
        this.cidades.add("Juramento");
        this.cidades.add("Juruaia");
        this.cidades.add("Juvenília");
        this.cidades.add("Ladainha");
        this.cidades.add("Lagamar");
        this.cidades.add("Lagoa da Prata");
        this.cidades.add("Lagoa dos Patos");
        this.cidades.add("Lagoa Dourada");
        this.cidades.add("Lagoa Formosa");
        this.cidades.add("Lagoa Grande");
        this.cidades.add("Lagoa Santa");
        this.cidades.add("Lajinha");
        this.cidades.add("Lambari");
        this.cidades.add("Lamim");
        this.cidades.add("Laranjal");
        this.cidades.add("Lassance");
        this.cidades.add("Lavras");
        this.cidades.add("Leandro Ferreira");
        this.cidades.add("Leme do Prado");
        this.cidades.add("Leopoldina");
        this.cidades.add("Liberdade");
        this.cidades.add("Lima Duarte");
        this.cidades.add("Limeira do Oeste");
        this.cidades.add("Lontra");
        this.cidades.add("Luisburgo");
        this.cidades.add("Luislândia");
        this.cidades.add("Luminárias");
        this.cidades.add("Luz");
        this.cidades.add("Machacalis");
        this.cidades.add("Machado");
        this.cidades.add("Madre de Deus de Minas");
        this.cidades.add("Malacacheta");
        this.cidades.add("Mamonas");
        this.cidades.add("Manga");
        this.cidades.add("Manhuaçu");
        this.cidades.add("Manhumirim");
        this.cidades.add("Mantena");
        this.cidades.add("Maravilhas");
        this.cidades.add("Mar de Espanha");
        this.cidades.add("Maria da Fé");
        this.cidades.add("Mariana");
        this.cidades.add("Marilac");
        this.cidades.add("Mário Campos");
        this.cidades.add("Maripá de Minas");
        this.cidades.add("Marliéria");
        this.cidades.add("Marmelópolis");
        this.cidades.add("Martinho Campos");
        this.cidades.add("Martins Soares");
        this.cidades.add("Mata Verde");
        this.cidades.add("Materlândia");
        this.cidades.add("Mateus Leme");
        this.cidades.add("Matias Barbosa");
        this.cidades.add("Matias Cardoso");
        this.cidades.add("Matipó");
        this.cidades.add("Mato Verde");
        this.cidades.add("Matozinhos");
        this.cidades.add("Matutina");
        this.cidades.add("Medeiros");
        this.cidades.add("Medina");
        this.cidades.add("Mendes Pimentel");
        this.cidades.add("Mercês");
        this.cidades.add("Mesquita");
        this.cidades.add("Minas Novas");
        this.cidades.add("Minduri");
        this.cidades.add("Mirabela");
        this.cidades.add("Miradouro");
        this.cidades.add("Miraí");
        this.cidades.add("Miravânia");
        this.cidades.add("Moeda");
        this.cidades.add("Moema");
        this.cidades.add("Monjolos");
        this.cidades.add("Monsenhor Paulo");
        this.cidades.add("Montalvânia");
        this.cidades.add("Monte Alegre de Minas");
        this.cidades.add("Monte Azul");
        this.cidades.add("Monte Belo");
        this.cidades.add("Monte Carmelo");
        this.cidades.add("Monte Formoso");
        this.cidades.add("Monte Santo de Minas");
        this.cidades.add("Montes Claros");
        this.cidades.add("Monte Sião");
        this.cidades.add("Montezuma");
        this.cidades.add("Morada Nova de Minas");
        this.cidades.add("Morro da Garça");
        this.cidades.add("Morro do Pilar");
        this.cidades.add("Munhoz");
        this.cidades.add("Muriaé");
        this.cidades.add("Mutum");
        this.cidades.add("Muzambinho");
        this.cidades.add("Nacip Raydan");
        this.cidades.add("Nanuque");
        this.cidades.add("Naque");
        this.cidades.add("Natalândia");
        this.cidades.add("Natércia");
        this.cidades.add("Nazareno");
        this.cidades.add("Nepomuceno");
        this.cidades.add("Ninheira");
        this.cidades.add("Nova Belém");
        this.cidades.add("Nova Era");
        this.cidades.add("Nova Lima");
        this.cidades.add("Nova Módica");
        this.cidades.add("Nova Ponte");
        this.cidades.add("Nova Porteirinha");
        this.cidades.add("Nova Resende");
        this.cidades.add("Nova Serrana");
        this.cidades.add("Novo Cruzeiro");
        this.cidades.add("Novo Oriente de Minas");
        this.cidades.add("Novorizonte");
        this.cidades.add("Olaria");
        this.cidades.add("Olhos-D'Água");
        this.cidades.add("Olímpio Noronha");
        this.cidades.add("Oliveira");
        this.cidades.add("Oliveira Fortes");
        this.cidades.add("Onça de Pitangui");
        this.cidades.add("Oratórios");
        this.cidades.add("Orizânia");
        this.cidades.add("Ouro Branco");
        this.cidades.add("Ouro Fino");
        this.cidades.add("Ouro Preto");
        this.cidades.add("Ouro Verde de Minas");
        this.cidades.add("Padre Carvalho");
        this.cidades.add("Padre Paraíso");
        this.cidades.add("Paineiras");
        this.cidades.add("Pains");
        this.cidades.add("Pai Pedro");
        this.cidades.add("Paiva");
        this.cidades.add("Palma");
        this.cidades.add("Palmópolis");
        this.cidades.add("Papagaios");
        this.cidades.add("Paracatu");
        this.cidades.add("Pará de Minas");
        this.cidades.add("Paraguaçu");
        this.cidades.add("Paraisópolis");
        this.cidades.add("Paraopeba");
        this.cidades.add("Passabém");
        this.cidades.add("Passa Quatro");
        this.cidades.add("Passa Tempo");
        this.cidades.add("Passa-Vinte");
        this.cidades.add("Passos");
        this.cidades.add("Patis");
        this.cidades.add("Patos de Minas");
        this.cidades.add("Patrocínio");
        this.cidades.add("Patrocínio do Muriaé");
        this.cidades.add("Paula Cândido");
        this.cidades.add("Paulistas");
        this.cidades.add("Pavão");
        this.cidades.add("Peçanha");
        this.cidades.add("Pedra Azul");
        this.cidades.add("Pedra Bonita");
        this.cidades.add("Pedra do Anta");
        this.cidades.add("Pedra do Indaiá");
        this.cidades.add("Pedra Dourada");
        this.cidades.add("Pedralva");
        this.cidades.add("Pedras de Maria da Cruz");
        this.cidades.add("Pedrinópolis");
        this.cidades.add("Pedro Leopoldo");
        this.cidades.add("Pedro Teixeira");
        this.cidades.add("Pequeri");
        this.cidades.add("Pequi");
        this.cidades.add("Perdigão");
        this.cidades.add("Perdizes");
        this.cidades.add("Perdões");
        this.cidades.add("Periquito");
        this.cidades.add("Pescador");
        this.cidades.add("Piau");
        this.cidades.add("Piedade de Caratinga");
        this.cidades.add("Piedade de Ponte Nova");
        this.cidades.add("Piedade do Rio Grande");
        this.cidades.add("Piedade dos Gerais");
        this.cidades.add("Pimenta");
        this.cidades.add("Pingo-D'Água");
        this.cidades.add("Pintópolis");
        this.cidades.add("Piracema");
        this.cidades.add("Pirajuba");
        this.cidades.add("Piranga");
        this.cidades.add("Piranguçu");
        this.cidades.add("Piranguinho");
        this.cidades.add("Pirapetinga");
        this.cidades.add("Pirapora");
        this.cidades.add("Piraúba");
        this.cidades.add("Pitangui");
        this.cidades.add("Piumhi");
        this.cidades.add("Planura");
        this.cidades.add("Poço Fundo");
        this.cidades.add("Poços de Caldas");
        this.cidades.add("Pocrane");
        this.cidades.add("Pompéu");
        this.cidades.add("Ponte Nova");
        this.cidades.add("Ponto Chique");
        this.cidades.add("Ponto dos Volantes");
        this.cidades.add("Porteirinha");
        this.cidades.add("Porto Firme");
        this.cidades.add("Poté");
        this.cidades.add("Pouso Alegre");
        this.cidades.add("Pouso Alto");
        this.cidades.add("Prados");
        this.cidades.add("Prata");
        this.cidades.add("Pratápolis");
        this.cidades.add("Pratinha");
        this.cidades.add("Presidente Bernardes");
        this.cidades.add("Presidente Juscelino");
        this.cidades.add("Presidente Kubitschek");
        this.cidades.add("Presidente Olegário");
        this.cidades.add("Alto Jequitibá");
        this.cidades.add("Prudente de Morais");
        this.cidades.add("Quartel Geral");
        this.cidades.add("Queluzito");
        this.cidades.add("Raposos");
        this.cidades.add("Raul Soares");
        this.cidades.add("Recreio");
        this.cidades.add("Reduto");
        this.cidades.add("Resende Costa");
        this.cidades.add("Resplendor");
        this.cidades.add("Ressaquinha");
        this.cidades.add("Riachinho");
        this.cidades.add("Riacho dos Machados");
        this.cidades.add("Ribeirão das Neves");
        this.cidades.add("Ribeirão Vermelho");
        this.cidades.add("Rio Acima");
        this.cidades.add("Rio Casca");
        this.cidades.add("Rio Doce");
        this.cidades.add("Rio do Prado");
        this.cidades.add("Rio Espera");
        this.cidades.add("Rio Manso");
        this.cidades.add("Rio Novo");
        this.cidades.add("Rio Paranaíba");
        this.cidades.add("Rio Pardo de Minas");
        this.cidades.add("Rio Piracicaba");
        this.cidades.add("Rio Pomba");
        this.cidades.add("Rio Preto");
        this.cidades.add("Rio Vermelho");
        this.cidades.add("Ritápolis");
        this.cidades.add("Rochedo de Minas");
        this.cidades.add("Rodeiro");
        this.cidades.add("Romaria");
        this.cidades.add("Rosário da Limeira");
        this.cidades.add("Rubelita");
        this.cidades.add("Rubim");
        this.cidades.add("Sabará");
        this.cidades.add("Sabinópolis");
        this.cidades.add("Sacramento");
        this.cidades.add("Salinas");
        this.cidades.add("Salto da Divisa");
        this.cidades.add("Santa Bárbara");
        this.cidades.add("Santa Bárbara do Leste");
        this.cidades.add("Santa Bárbara do Monte Verde");
        this.cidades.add("Santa Bárbara do Tugúrio");
        this.cidades.add("Santa Cruz de Minas");
        this.cidades.add("Santa Cruz de Salinas");
        this.cidades.add("Santa Cruz do Escalvado");
        this.cidades.add("Santa Efigênia de Minas");
        this.cidades.add("Santa Fé de Minas");
        this.cidades.add("Santa Helena de Minas");
        this.cidades.add("Santa Juliana");
        this.cidades.add("Santa Luzia");
        this.cidades.add("Santa Margarida");
        this.cidades.add("Santa Maria de Itabira");
        this.cidades.add("Santa Maria do Salto");
        this.cidades.add("Santa Maria do Suaçuí");
        this.cidades.add("Santana da Vargem");
        this.cidades.add("Santana de Cataguases");
        this.cidades.add("Santana de Pirapama");
        this.cidades.add("Santana do Deserto");
        this.cidades.add("Santana do Garambéu");
        this.cidades.add("Santana do Jacaré");
        this.cidades.add("Santana do Manhuaçu");
        this.cidades.add("Santana do Paraíso");
        this.cidades.add("Santana do Riacho");
        this.cidades.add("Santana dos Montes");
        this.cidades.add("Santa Rita de Caldas");
        this.cidades.add("Santa Rita de Jacutinga");
        this.cidades.add("Santa Rita de Minas");
        this.cidades.add("Santa Rita de Ibitipoca");
        this.cidades.add("Santa Rita do Itueto");
        this.cidades.add("Santa Rita do Sapucaí");
        this.cidades.add("Santa Rosa da Serra");
        this.cidades.add("Santa Vitória");
        this.cidades.add("Santo Antônio do Amparo");
        this.cidades.add("Santo Antônio do Aventureiro");
        this.cidades.add("Santo Antônio do Grama");
        this.cidades.add("Santo Antônio do Itambé");
        this.cidades.add("Santo Antônio do Jacinto");
        this.cidades.add("Santo Antônio do Monte");
        this.cidades.add("Santo Antônio do Retiro");
        this.cidades.add("Santo Antônio do Rio Abaixo");
        this.cidades.add("Santo Hipólito");
        this.cidades.add("Santos Dumont");
        this.cidades.add("São Bento Abade");
        this.cidades.add("São Brás do Suaçuí");
        this.cidades.add("São Domingos das Dores");
        this.cidades.add("São Domingos do Prata");
        this.cidades.add("São Félix de Minas");
        this.cidades.add("São Francisco");
        this.cidades.add("São Francisco de Paula");
        this.cidades.add("São Francisco de Sales");
        this.cidades.add("São Francisco do Glória");
        this.cidades.add("São Geraldo");
        this.cidades.add("São Geraldo da Piedade");
        this.cidades.add("São Geraldo do Baixio");
        this.cidades.add("São Gonçalo do Abaeté");
        this.cidades.add("São Gonçalo do Pará");
        this.cidades.add("São Gonçalo do Rio Abaixo");
        this.cidades.add("São Gonçalo do Sapucaí");
        this.cidades.add("São Gotardo");
        this.cidades.add("São João Batista do Glória");
        this.cidades.add("São João da Lagoa");
        this.cidades.add("São João da Mata");
        this.cidades.add("São João da Ponte");
        this.cidades.add("São João das Missões");
        this.cidades.add("São João del Rei");
        this.cidades.add("São João do Manhuaçu");
        this.cidades.add("São João do Manteninha");
        this.cidades.add("São João do Oriente");
        this.cidades.add("São João do Pacuí");
        this.cidades.add("São João do Paraíso");
        this.cidades.add("São João Evangelista");
        this.cidades.add("São João Nepomuceno");
        this.cidades.add("São Joaquim de Bicas");
        this.cidades.add("São José da Barra");
        this.cidades.add("São José da Lapa");
        this.cidades.add("São José da Safira");
        this.cidades.add("São José da Varginha");
        this.cidades.add("São José do Alegre");
        this.cidades.add("São José do Divino");
        this.cidades.add("São José do Goiabal");
        this.cidades.add("São José do Jacuri");
        this.cidades.add("São José do Mantimento");
        this.cidades.add("São Lourenço");
        this.cidades.add("São Miguel do Anta");
        this.cidades.add("São Pedro da União");
        this.cidades.add("São Pedro dos Ferros");
        this.cidades.add("São Pedro do Suaçuí");
        this.cidades.add("São Romão");
        this.cidades.add("São Roque de Minas");
        this.cidades.add("São Sebastião da Bela Vista");
        this.cidades.add("São Sebastião da Vargem Alegre");
        this.cidades.add("São Sebastião do Anta");
        this.cidades.add("São Sebastião do Maranhão");
        this.cidades.add("São Sebastião do Oeste");
        this.cidades.add("São Sebastião do Paraíso");
        this.cidades.add("São Sebastião do Rio Preto");
        this.cidades.add("São Sebastião do Rio Verde");
        this.cidades.add("São Tiago");
        this.cidades.add("São Tomás de Aquino");
        this.cidades.add("São Thomé das Letras");
        this.cidades.add("São Vicente de Minas");
        this.cidades.add("Sapucaí-Mirim");
        this.cidades.add("Sardoá");
        this.cidades.add("Sarzedo");
        this.cidades.add("Setubinha");
        this.cidades.add("Sem-Peixe");
        this.cidades.add("Senador Amaral");
        this.cidades.add("Senador Cortes");
        this.cidades.add("Senador Firmino");
        this.cidades.add("Senador José Bento");
        this.cidades.add("Senador Modestino Gonçalves");
        this.cidades.add("Senhora de Oliveira");
        this.cidades.add("Senhora do Porto");
        this.cidades.add("Senhora dos Remédios");
        this.cidades.add("Sericita");
        this.cidades.add("Seritinga");
        this.cidades.add("Serra Azul de Minas");
        this.cidades.add("Serra da Saudade");
        this.cidades.add("Serra dos Aimorés");
        this.cidades.add("Serra do Salitre");
        this.cidades.add("Serrania");
        this.cidades.add("Serranópolis de Minas");
        this.cidades.add("Serranos");
        this.cidades.add("Serro");
        this.cidades.add("Sete Lagoas");
        this.cidades.add("Silveirânia");
        this.cidades.add("Silvianópolis");
        this.cidades.add("Simão Pereira");
        this.cidades.add("Simonésia");
        this.cidades.add("Sobrália");
        this.cidades.add("Soledade de Minas");
        this.cidades.add("Tabuleiro");
        this.cidades.add("Taiobeiras");
        this.cidades.add("Taparuba");
        this.cidades.add("Tapira");
        this.cidades.add("Tapiraí");
        this.cidades.add("Taquaraçu de Minas");
        this.cidades.add("Tarumirim");
        this.cidades.add("Teixeiras");
        this.cidades.add("Teófilo Otoni");
        this.cidades.add("Timóteo");
        this.cidades.add("Tiradentes");
        this.cidades.add("Tiros");
        this.cidades.add("Tocantins");
        this.cidades.add("Tocos do Moji");
        this.cidades.add("Toledo");
        this.cidades.add("Tombos");
        this.cidades.add("Três Corações");
        this.cidades.add("Três Marias");
        this.cidades.add("Três Pontas");
        this.cidades.add("Tumiritinga");
        this.cidades.add("Tupaciguara");
        this.cidades.add("Turmalina");
        this.cidades.add("Turvolândia");
        this.cidades.add("Ubá");
        this.cidades.add("Ubaí");
        this.cidades.add("Ubaporanga");
        this.cidades.add("Uberaba");
        this.cidades.add("Uberlândia");
        this.cidades.add("Umburatiba");
        this.cidades.add("Unaí");
        this.cidades.add("União de Minas");
        this.cidades.add("Uruana de Minas");
        this.cidades.add("Urucânia");
        this.cidades.add("Urucuia");
        this.cidades.add("Vargem Alegre");
        this.cidades.add("Vargem Bonita");
        this.cidades.add("Vargem Grande do Rio Pardo");
        this.cidades.add("Varginha");
        this.cidades.add("Varjão de Minas");
        this.cidades.add("Várzea da Palma");
        this.cidades.add("Varzelândia");
        this.cidades.add("Vazante");
        this.cidades.add("Verdelândia");
        this.cidades.add("Veredinha");
        this.cidades.add("Veríssimo");
        this.cidades.add("Vermelho Novo");
        this.cidades.add("Vespasiano");
        this.cidades.add("Viçosa");
        this.cidades.add("Vieiras");
        this.cidades.add("Mathias Lobato");
        this.cidades.add("Virgem da Lapa");
        this.cidades.add("Virgínia");
        this.cidades.add("Virginópolis");
        this.cidades.add("Virgolândia");
        this.cidades.add("Visconde do Rio Branco");
        this.cidades.add("Volta Grande");
        this.cidades.add("Wenceslau Braz");
        this.cidades.add("Abadia dos Dourados");
        this.cidades.add("Abaeté");
        this.cidades.add("Abre Campo");
        this.cidades.add("Acaiaca");
        this.cidades.add("Açucena");
        this.cidades.add("Água Boa");
        this.cidades.add("Água Comprida");
        this.cidades.add("Aguanil");
        this.cidades.add("Águas Formosas");
        this.cidades.add("Águas Vermelhas");
        this.cidades.add("Aimorés");
        this.cidades.add("Aiuruoca");
        this.cidades.add("Alagoa");
        this.cidades.add("Albertina");
        this.cidades.add("Além Paraíba");
        this.cidades.add("Alfenas");
        this.cidades.add("Alfredo Vasconcelos");
        this.cidades.add("Almenara");
        this.cidades.add("Alpercata");
        this.cidades.add("Alpinópolis");
        this.cidades.add("Alterosa");
        this.cidades.add("Alto Caparaó");
        this.cidades.add("Alto Rio Doce");
        this.cidades.add("Alvarenga");
        this.cidades.add("Alvinópolis");
        this.cidades.add("Alvorada de Minas");
        this.cidades.add("Amparo do Serra");
        this.cidades.add("Andradas");
        this.cidades.add("Cachoeira de Pajeú");
        this.cidades.add("Andrelândia");
        this.cidades.add("Angelândia");
        this.cidades.add("Antônio Carlos");
        this.cidades.add("Antônio Dias");
        this.cidades.add("Antônio Prado de Minas");
        this.cidades.add("Araçaí");
        this.cidades.add("Aracitaba");
        this.cidades.add("Araçuaí");
        this.cidades.add("Araguari");
        this.cidades.add("Arantina");
        this.cidades.add("Araponga");
        this.cidades.add("Araporã");
        this.cidades.add("Arapuá");
        this.cidades.add("Araújos");
        this.cidades.add("Araxá");
        this.cidades.add("Arceburgo");
        this.cidades.add("Arcos");
        this.cidades.add("Areado");
        this.cidades.add("Argirita");
        this.cidades.add("Aricanduva");
        this.cidades.add("Arinos");
        this.cidades.add("Astolfo Dutra");
        this.cidades.add("Ataléia");
        this.cidades.add("Augusto de Lima");
        this.cidades.add("Baependi");
        this.cidades.add("Baldim");
        this.cidades.add("Bambuí");
        this.cidades.add("Bandeira");
        this.cidades.add("Bandeira do Sul");
        this.cidades.add("Barão de Cocais");
        this.cidades.add("Barão de Monte Alto");
        this.cidades.add("Barbacena");
        this.cidades.add("Barra Longa");
        this.cidades.add("Barroso");
        this.cidades.add("Bela Vista de Minas");
        this.cidades.add("Belmiro Braga");
        this.cidades.add("Belo Horizonte");
        this.cidades.add("Belo Oriente");
        this.cidades.add("Belo Vale");
        this.cidades.add("Berilo");
        this.cidades.add("Bertópolis");
        this.cidades.add("Berizal");
        this.cidades.add("Betim");
        this.cidades.add("Bias Fortes");
        this.cidades.add("Bicas");
        this.cidades.add("Biquinhas");
        this.cidades.add("Boa Esperança");
        this.cidades.add("Bocaina de Minas");
        this.cidades.add("Bocaiúva");
        this.cidades.add("Bom Despacho");
        this.cidades.add("Bom Jardim de Minas");
        this.cidades.add("Bom Jesus da Penha");
        this.cidades.add("Bom Jesus do Amparo");
        this.cidades.add("Bom Jesus do Galho");
        this.cidades.add("Bom Repouso");
        this.cidades.add("Bom Sucesso");
        this.cidades.add("Bonfim");
        this.cidades.add("Bonfinópolis de Minas");
        this.cidades.add("Bonito de Minas");
        this.cidades.add("Borda da Mata");
        this.cidades.add("Botelhos");
        this.cidades.add("Botumirim");
        this.cidades.add("Brasilândia de Minas");
        this.cidades.add("Brasília de Minas");
        this.cidades.add("Brás Pires");
        this.cidades.add("Braúnas");
        this.cidades.add("Brazópolis");
        this.cidades.add("Brumadinho");
        this.cidades.add("Bueno Brandão");
        this.cidades.add("Buenópolis");
        this.cidades.add("Bugre");
        this.cidades.add("Buritis");
        this.cidades.add("Buritizeiro");
        this.cidades.add("Cabeceira Grande");
        this.cidades.add("Cabo Verde");
        this.cidades.add("Cachoeira da Prata");
        this.cidades.add("Cachoeira de Minas");
        this.cidades.add("Cachoeira Dourada");
        this.cidades.add("Caetanópolis");
        this.cidades.add("Caeté");
        this.cidades.add("Caiana");
        this.cidades.add("Cajuri");
        this.cidades.add("Caldas");
        this.cidades.add("Camacho");
        this.cidades.add("Camanducaia");
        this.cidades.add("Cambuí");
        this.cidades.add("Cambuquira");
        this.cidades.add("Campanário");
        this.cidades.add("Campanha");
        this.cidades.add("Campestre");
        this.cidades.add("Campina Verde");
        this.cidades.add("Campo Azul");
        this.cidades.add("Campo Belo");
        this.cidades.add("Campo do Meio");
        this.cidades.add("Campo Florido");
        this.cidades.add("Campos Altos");
        this.cidades.add("Campos Gerais");
        this.cidades.add("Canaã");
        this.cidades.add("Canápolis");
        this.cidades.add("Cana Verde");
        this.cidades.add("Candeias");
        this.cidades.add("Cantagalo");
        this.cidades.add("Caparaó");
        this.cidades.add("Capela Nova");
        this.cidades.add("Capelinha");
        this.cidades.add("Capetinga");
        this.cidades.add("Capim Branco");
        this.cidades.add("Capinópolis");
        this.cidades.add("Capitão Andrade");
        this.cidades.add("Capitão Enéas");
        this.cidades.add("Capitólio");
        this.cidades.add("Caputira");
        this.cidades.add("Caraí");
        this.cidades.add("Caranaíba");
        this.cidades.add("Carandaí");
        this.cidades.add("Carangola");
        this.cidades.add("Caratinga");
        this.cidades.add("Carbonita");
        this.cidades.add("Careaçu");
        this.cidades.add("Carlos Chagas");
        this.cidades.add("Carmésia");
        this.cidades.add("Carmo da Cachoeira");
        this.cidades.add("Carmo da Mata");
        this.cidades.add("Carmo de Minas");
        this.cidades.add("Carmo do Cajuru");
        this.cidades.add("Carmo do Paranaíba");
        this.cidades.add("Carmo do Rio Claro");
        this.cidades.add("Carmópolis de Minas");
        this.cidades.add("Carneirinho");
        this.cidades.add("Carrancas");
        this.cidades.add("Carvalhópolis");
        this.cidades.add("Carvalhos");
        this.cidades.add("Casa Grande");
        this.cidades.add("Cascalho Rico");
        this.cidades.add("Cássia");
        this.cidades.add("Conceição da Barra de Minas");
        this.cidades.add("Cataguases");
        this.cidades.add("Catas Altas");
        this.cidades.add("Catas Altas da Noruega");
        this.cidades.add("Catuji");
        this.cidades.add("Catuti");
        this.cidades.add("Caxambu");
        this.cidades.add("Cedro do Abaeté");
        this.cidades.add("Central de Minas");
        this.cidades.add("Centralina");
        this.cidades.add("Chácara");
        this.cidades.add("Chalé");
        this.cidades.add("Chapada do Norte");
        this.cidades.add("Chapada Gaúcha");
        this.cidades.add("Chiador");
        this.cidades.add("Cipotânea");
        this.cidades.add("Claraval");
        this.cidades.add("Claro dos Poções");
        this.cidades.add("Cláudio");
        this.cidades.add("Coimbra");
        this.cidades.add("Coluna");
        this.cidades.add("Comendador Gomes");
        this.cidades.add("Comercinho");
        this.cidades.add("Conceição da Aparecida");
        this.cidades.add("Conceição das Pedras");
        this.cidades.add("Conceição das Alagoas");
        this.cidades.add("Conceição de Ipanema");
        this.cidades.add("Conceição do Mato Dentro");
        this.cidades.add("Conceição do Pará");
        this.cidades.add("Conceição do Rio Verde");
        this.cidades.add("Conceição dos Ouros");
        this.cidades.add("Cônego Marinho");
        this.cidades.add("Confins");
        this.cidades.add("Congonhal");
        this.cidades.add("Congonhas");
        this.cidades.add("Congonhas do Norte");
        this.cidades.add("Conquista");
        this.cidades.add("Conselheiro Lafaiete");
        this.cidades.add("Conselheiro Pena");
        this.cidades.add("Consolação");
        this.cidades.add("Contagem");
        this.cidades.add("Coqueiral");
        this.cidades.add("Coração de Jesus");
        this.cidades.add("Cordisburgo");
        this.cidades.add("Cordislândia");
        this.cidades.add("Corinto");
        this.cidades.add("Coroaci");
        this.cidades.add("Coromandel");
        this.cidades.add("Coronel Fabriciano");
        this.cidades.add("Coronel Murta");
        this.cidades.add("Coronel Pacheco");
        this.cidades.add("Coronel Xavier Chaves");
        this.cidades.add("Córrego Danta");
        this.cidades.add("Córrego do Bom Jesus");
        this.cidades.add("Córrego Fundo");
        this.cidades.add("Córrego Novo");
        this.cidades.add("Couto de Magalhães de Minas");
        this.cidades.add("Crisólita");
        this.cidades.add("Cristais");
        this.cidades.add("Cristália");
        this.cidades.add("Cristiano Otoni");
        this.cidades.add("Cristina");
        this.cidades.add("Crucilândia");
        this.cidades.add("Cruzeiro da Fortaleza");
        this.cidades.add("Cruzília");
        this.cidades.add("Cuparaque");
        this.cidades.add("Curral de Dentro");
        this.cidades.add("Curvelo");
        this.cidades.add("Datas");
        this.cidades.add("Delfim Moreira");
        this.cidades.add("Delfinópolis");
        this.cidades.add("Delta");
        this.cidades.add("Descoberto");
        this.cidades.add("Desterro de Entre Rios");
        this.cidades.add("Desterro do Melo");
        this.cidades.add("Diamantina");
        this.cidades.add("Diogo de Vasconcelos");
        this.cidades.add("Dionísio");
        this.cidades.add("Divinésia");
        this.cidades.add("Divino");
        this.cidades.add("Divino das Laranjeiras");
        this.cidades.add("Divinolândia de Minas");
        this.cidades.add("Divinópolis");
        this.cidades.add("Divisa Alegre");
        this.cidades.add("Divisa Nova");
        this.cidades.add("Divisópolis");
        this.cidades.add("Dom Bosco");
        this.cidades.add("Dom Cavati");
        this.cidades.add("Dom Joaquim");
        this.cidades.add("Dom Silvério");
        this.cidades.add("Dom Viçoso");
        this.cidades.add("Dona Eusébia");
        this.cidades.add("Dores de Campos");
        this.cidades.add("Dores de Guanhães");
        this.cidades.add("Dores do Indaiá");
        this.cidades.add("Dores do Turvo");
        this.cidades.add("Doresópolis");
        this.cidades.add("Douradoquara");
        this.cidades.add("Durandé");
        this.cidades.add("Elói Mendes");
        this.cidades.add("Engenheiro Caldas");
        this.cidades.add("Engenheiro Navarro");
        this.cidades.add("Entre Folhas");
        this.cidades.add("Entre Rios de Minas");
        this.cidades.add("Ervália");
        this.cidades.add("Esmeraldas");
        this.cidades.add("Espera Feliz");
        this.cidades.add("Espinosa");
        this.cidades.add("Espírito Santo do Dourado");
        this.cidades.add("Estiva");
        this.cidades.add("Estrela Dalva");
        this.cidades.add("Estrela do Indaiá");
        this.cidades.add("Estrela do Sul");
        this.cidades.add("Eugenópolis");
        this.cidades.add("Ewbank da Câmara");
        this.cidades.add("Extrema");
        this.cidades.add("Fama");
        this.cidades.add("Faria Lemos");
        this.cidades.add("Felício dos Santos");
        this.cidades.add("São Gonçalo do Rio Preto");
        this.cidades.add("Felisburgo");
        this.cidades.add("Felixlândia");
        this.cidades.add("Fernandes Tourinho");
        this.cidades.add("Ferros");
        this.cidades.add("Fervedouro");
        this.cidades.add("Florestal");
        this.cidades.add("Formiga");
        this.cidades.add("Formoso");
        this.cidades.add("Fortaleza de Minas");
        this.cidades.add("Fortuna de Minas");
        this.cidades.add("Francisco Badaró");
        this.cidades.add("Francisco Dumont");
        this.cidades.add("Francisco Sá");
        this.cidades.add("Franciscópolis");
        this.cidades.add("Frei Gaspar");
        this.cidades.add("Frei Inocêncio");
        this.cidades.add("Frei Lagonegro");
        this.cidades.add("Fronteira");
        this.cidades.add("Fronteira dos Vales");
        this.cidades.add("Fruta de Leite");
        this.cidades.add("Frutal");
        this.cidades.add("Funilândia");
        this.cidades.add("Galiléia");
        this.cidades.add("Gameleiras");
        this.cidades.add("Glaucilândia");
        this.cidades.add("Goiabeira");
        this.cidades.add("Goianá");
        this.cidades.add("Gonçalves");
        this.cidades.add("Gonzaga");
        this.cidades.add("Gouveia");
        this.cidades.add("Governador Valadares");
        this.cidades.add("Grão Mogol");
        this.cidades.add("Grupiara");
        this.cidades.add("Guanhães");
        this.cidades.add("Guapé");
        this.cidades.add("Guaraciaba");
        this.cidades.add("Guaraciama");
        this.cidades.add("Guaranésia");
        this.cidades.add("Guarani");
        this.cidades.add("Guarará");
        this.cidades.add("Guarda-Mor");
        this.cidades.add("Guaxupé");
        this.cidades.add("Guidoval");
        this.cidades.add("Guimarânia");
        this.cidades.add("Guiricema");
        this.cidades.add("Gurinhatã");
        this.cidades.add("Heliodora");
        this.cidades.add("Iapu");
        this.cidades.add("Ibertioga");
        this.cidades.add("Ibiá");
        this.cidades.add("Ibiaí");
        this.cidades.add("Ibiracatu");
        this.cidades.add("Ibiraci");
        this.cidades.add("Ibirité");
        this.cidades.add("Ibitiúra de Minas");
        this.cidades.add("Ibituruna");
        this.cidades.add("Icaraí de Minas");
        this.cidades.add("Igarapé");
        this.cidades.add("Igaratinga");
        this.cidades.add("Iguatama");
        this.cidades.add("Ijaci");
        this.cidades.add("Ilicínea");
        this.cidades.add("Imbé de Minas");
        this.cidades.add("Inconfidentes");
        this.cidades.add("Indaiabira");
        this.cidades.add("Indianópolis");
        this.cidades.add("Ingaí");
        this.cidades.add("Inhapim");
        this.cidades.add("Inhaúma");
        this.cidades.add("Inimutaba");
        this.cidades.add("Ipaba");
        this.cidades.add("Ipanema");
        this.cidades.add("Ipatinga");
        this.cidades.add("Ipiaçu");
        this.cidades.add("Ipuiúna");
        this.cidades.add("Iraí de Minas");
        this.cidades.add("Itabira");
        this.cidades.add("Itabirinha");
        this.cidades.add("Itabirito");
        this.cidades.add("Itacambira");
        this.cidades.add("Itacarambi");
        this.cidades.add("Itaguara");
        this.cidades.add("Itaipé");
        this.cidades.add("Itajubá");
        this.cidades.add("Itamarandiba");
        this.cidades.add("Itamarati de Minas");
        this.cidades.add("Itambacuri");
        this.cidades.add("Itambé do Mato Dentro");
        this.cidades.add("Itamogi");
        this.cidades.add("Itamonte");
        this.cidades.add("Itanhandu");
        this.cidades.add("Itanhomi");
        this.cidades.add("Itaobim");
        this.cidades.add("Itapagipe");
        this.cidades.add("Itapecerica");
        this.cidades.add("Itapeva");
        this.cidades.add("Itatiaiuçu");
        this.cidades.add("Itaú de Minas");
        this.cidades.add("Itaúna");
        this.cidades.add("Itaverava");
        this.cidades.add("Itinga");
        this.cidades.add("Itueta");
        this.cidades.add("Ituiutaba");
        this.cidades.add("Itumirim");
        this.cidades.add("Iturama");
        this.cidades.add("Itutinga");
        this.cidades.add("Jaboticatubas");
        this.cidades.add("Jacinto");
        this.cidades.add("Jacuí");
        this.cidades.add("Jacutinga");
        this.cidades.add("Jaguaraçu");
        this.cidades.add("Jaíba");
        this.cidades.add("Jampruca");
        this.cidades.add("Janaúba");
        this.cidades.add("Januária");
        this.cidades.add("Japaraíba");
        this.cidades.add("Japonvar");
        this.cidades.add("Jeceaba");
        this.cidades.add("Jenipapo de Minas");
        this.cidades.add("Jequeri");
        this.cidades.add("Jequitaí");
        this.cidades.add("Jequitibá");
        this.cidades.add("Jequitinhonha");
        this.cidades.add("Jesuânia");
        this.cidades.add("Joaíma");
        this.cidades.add("Joanésia");
        this.cidades.add("João Monlevade");
        this.cidades.add("João Pinheiro");
        this.cidades.add("Joaquim Felício");
        this.cidades.add("Jordânia");
        this.cidades.add("José Gonçalves de Minas");
        this.cidades.add("José Raydan");
        this.cidades.add("Josenópolis");
        this.cidades.add("Nova União");
        this.cidades.add("Juatuba");
        this.cidades.add("Juiz de Fora");
        this.cidades.add("Juramento");
        this.cidades.add("Juruaia");
        this.cidades.add("Juvenília");
        this.cidades.add("Ladainha");
        this.cidades.add("Lagamar");
        this.cidades.add("Lagoa da Prata");
        this.cidades.add("Lagoa dos Patos");
        this.cidades.add("Lagoa Dourada");
        this.cidades.add("Lagoa Formosa");
        this.cidades.add("Lagoa Grande");
        this.cidades.add("Lagoa Santa");
        this.cidades.add("Lajinha");
        this.cidades.add("Lambari");
        this.cidades.add("Lamim");
        this.cidades.add("Laranjal");
        this.cidades.add("Lassance");
        this.cidades.add("Lavras");
        this.cidades.add("Leandro Ferreira");
        this.cidades.add("Leme do Prado");
        this.cidades.add("Leopoldina");
        this.cidades.add("Liberdade");
        this.cidades.add("Lima Duarte");
        this.cidades.add("Limeira do Oeste");
        this.cidades.add("Lontra");
        this.cidades.add("Luisburgo");
        this.cidades.add("Luislândia");
        this.cidades.add("Luminárias");
        this.cidades.add("Luz");
        this.cidades.add("Machacalis");
        this.cidades.add("Machado");
        this.cidades.add("Madre de Deus de Minas");
        this.cidades.add("Malacacheta");
        this.cidades.add("Mamonas");
        this.cidades.add("Manga");
        this.cidades.add("Manhuaçu");
        this.cidades.add("Manhumirim");
        this.cidades.add("Mantena");
        this.cidades.add("Maravilhas");
        this.cidades.add("Mar de Espanha");
        this.cidades.add("Maria da Fé");
        this.cidades.add("Mariana");
        this.cidades.add("Marilac");
        this.cidades.add("Mário Campos");
        this.cidades.add("Maripá de Minas");
        this.cidades.add("Marliéria");
        this.cidades.add("Marmelópolis");
        this.cidades.add("Martinho Campos");
        this.cidades.add("Martins Soares");
        this.cidades.add("Mata Verde");
        this.cidades.add("Materlândia");
        this.cidades.add("Mateus Leme");
        this.cidades.add("Matias Barbosa");
        this.cidades.add("Matias Cardoso");
        this.cidades.add("Matipó");
        this.cidades.add("Mato Verde");
        this.cidades.add("Matozinhos");
        this.cidades.add("Matutina");
        this.cidades.add("Medeiros");
        this.cidades.add("Medina");
        this.cidades.add("Mendes Pimentel");
        this.cidades.add("Mercês");
        this.cidades.add("Mesquita");
        this.cidades.add("Minas Novas");
        this.cidades.add("Minduri");
        this.cidades.add("Mirabela");
        this.cidades.add("Miradouro");
        this.cidades.add("Miraí");
        this.cidades.add("Miravânia");
        this.cidades.add("Moeda");
        this.cidades.add("Moema");
        this.cidades.add("Monjolos");
        this.cidades.add("Monsenhor Paulo");
        this.cidades.add("Montalvânia");
        this.cidades.add("Monte Alegre de Minas");
        this.cidades.add("Monte Azul");
        this.cidades.add("Monte Belo");
        this.cidades.add("Monte Carmelo");
        this.cidades.add("Monte Formoso");
        this.cidades.add("Monte Santo de Minas");
        this.cidades.add("Montes Claros");
        this.cidades.add("Monte Sião");
        this.cidades.add("Montezuma");
        this.cidades.add("Morada Nova de Minas");
        this.cidades.add("Morro da Garça");
        this.cidades.add("Morro do Pilar");
        this.cidades.add("Munhoz");
        this.cidades.add("Muriaé");
        this.cidades.add("Mutum");
        this.cidades.add("Muzambinho");
        this.cidades.add("Nacip Raydan");
        this.cidades.add("Nanuque");
        this.cidades.add("Naque");
        this.cidades.add("Natalândia");
        this.cidades.add("Natércia");
        this.cidades.add("Nazareno");
        this.cidades.add("Nepomuceno");
        this.cidades.add("Ninheira");
        this.cidades.add("Nova Belém");
        this.cidades.add("Nova Era");
        this.cidades.add("Nova Lima");
        this.cidades.add("Nova Módica");
        this.cidades.add("Nova Ponte");
        this.cidades.add("Nova Porteirinha");
        this.cidades.add("Nova Resende");
        this.cidades.add("Nova Serrana");
        this.cidades.add("Novo Cruzeiro");
        this.cidades.add("Novo Oriente de Minas");
        this.cidades.add("Novorizonte");
        this.cidades.add("Olaria");
        this.cidades.add("Olhos-D'Água");
        this.cidades.add("Olímpio Noronha");
        this.cidades.add("Oliveira");
        this.cidades.add("Oliveira Fortes");
        this.cidades.add("Onça de Pitangui");
        this.cidades.add("Oratórios");
        this.cidades.add("Orizânia");
        this.cidades.add("Ouro Branco");
        this.cidades.add("Ouro Fino");
        this.cidades.add("Ouro Preto");
        this.cidades.add("Ouro Verde de Minas");
        this.cidades.add("Padre Carvalho");
        this.cidades.add("Padre Paraíso");
        this.cidades.add("Paineiras");
        this.cidades.add("Pains");
        this.cidades.add("Pai Pedro");
        this.cidades.add("Paiva");
        this.cidades.add("Palma");
        this.cidades.add("Palmópolis");
        this.cidades.add("Papagaios");
        this.cidades.add("Paracatu");
        this.cidades.add("Pará de Minas");
        this.cidades.add("Paraguaçu");
        this.cidades.add("Paraisópolis");
        this.cidades.add("Paraopeba");
        this.cidades.add("Passabém");
        this.cidades.add("Passa Quatro");
        this.cidades.add("Passa Tempo");
        this.cidades.add("Passa-Vinte");
        this.cidades.add("Passos");
        this.cidades.add("Patis");
        this.cidades.add("Patos de Minas");
        this.cidades.add("Patrocínio");
        this.cidades.add("Patrocínio do Muriaé");
        this.cidades.add("Paula Cândido");
        this.cidades.add("Paulistas");
        this.cidades.add("Pavão");
        this.cidades.add("Peçanha");
        this.cidades.add("Pedra Azul");
        this.cidades.add("Pedra Bonita");
        this.cidades.add("Pedra do Anta");
        this.cidades.add("Pedra do Indaiá");
        this.cidades.add("Pedra Dourada");
        this.cidades.add("Pedralva");
        this.cidades.add("Pedras de Maria da Cruz");
        this.cidades.add("Pedrinópolis");
        this.cidades.add("Pedro Leopoldo");
        this.cidades.add("Pedro Teixeira");
        this.cidades.add("Pequeri");
        this.cidades.add("Pequi");
        this.cidades.add("Perdigão");
        this.cidades.add("Perdizes");
        this.cidades.add("Perdões");
        this.cidades.add("Periquito");
        this.cidades.add("Pescador");
        this.cidades.add("Piau");
        this.cidades.add("Piedade de Caratinga");
        this.cidades.add("Piedade de Ponte Nova");
        this.cidades.add("Piedade do Rio Grande");
        this.cidades.add("Piedade dos Gerais");
        this.cidades.add("Pimenta");
        this.cidades.add("Pingo-D'Água");
        this.cidades.add("Pintópolis");
        this.cidades.add("Piracema");
        this.cidades.add("Pirajuba");
        this.cidades.add("Piranga");
        this.cidades.add("Piranguçu");
        this.cidades.add("Piranguinho");
        this.cidades.add("Pirapetinga");
        this.cidades.add("Pirapora");
        this.cidades.add("Piraúba");
        this.cidades.add("Pitangui");
        this.cidades.add("Piumhi");
        this.cidades.add("Planura");
        this.cidades.add("Poço Fundo");
        this.cidades.add("Poços de Caldas");
        this.cidades.add("Pocrane");
        this.cidades.add("Pompéu");
        this.cidades.add("Ponte Nova");
        this.cidades.add("Ponto Chique");
        this.cidades.add("Ponto dos Volantes");
        this.cidades.add("Porteirinha");
        this.cidades.add("Porto Firme");
        this.cidades.add("Poté");
        this.cidades.add("Pouso Alegre");
        this.cidades.add("Pouso Alto");
        this.cidades.add("Prados");
        this.cidades.add("Prata");
        this.cidades.add("Pratápolis");
        this.cidades.add("Pratinha");
        this.cidades.add("Presidente Bernardes");
        this.cidades.add("Presidente Juscelino");
        this.cidades.add("Presidente Kubitschek");
        this.cidades.add("Presidente Olegário");
        this.cidades.add("Alto Jequitibá");
        this.cidades.add("Prudente de Morais");
        this.cidades.add("Quartel Geral");
        this.cidades.add("Queluzito");
        this.cidades.add("Raposos");
        this.cidades.add("Raul Soares");
        this.cidades.add("Recreio");
        this.cidades.add("Reduto");
        this.cidades.add("Resende Costa");
        this.cidades.add("Resplendor");
        this.cidades.add("Ressaquinha");
        this.cidades.add("Riachinho");
        this.cidades.add("Riacho dos Machados");
        this.cidades.add("Ribeirão das Neves");
        this.cidades.add("Ribeirão Vermelho");
        this.cidades.add("Rio Acima");
        this.cidades.add("Rio Casca");
        this.cidades.add("Rio Doce");
        this.cidades.add("Rio do Prado");
        this.cidades.add("Rio Espera");
        this.cidades.add("Rio Manso");
        this.cidades.add("Rio Novo");
        this.cidades.add("Rio Paranaíba");
        this.cidades.add("Rio Pardo de Minas");
        this.cidades.add("Rio Piracicaba");
        this.cidades.add("Rio Pomba");
        this.cidades.add("Rio Preto");
        this.cidades.add("Rio Vermelho");
        this.cidades.add("Ritápolis");
        this.cidades.add("Rochedo de Minas");
        this.cidades.add("Rodeiro");
        this.cidades.add("Romaria");
        this.cidades.add("Rosário da Limeira");
        this.cidades.add("Rubelita");
        this.cidades.add("Rubim");
        this.cidades.add("Sabará");
        this.cidades.add("Sabinópolis");
        this.cidades.add("Sacramento");
        this.cidades.add("Salinas");
        this.cidades.add("Salto da Divisa");
        this.cidades.add("Santa Bárbara");
        this.cidades.add("Santa Bárbara do Leste");
        this.cidades.add("Santa Bárbara do Monte Verde");
        this.cidades.add("Santa Bárbara do Tugúrio");
        this.cidades.add("Santa Cruz de Minas");
        this.cidades.add("Santa Cruz de Salinas");
        this.cidades.add("Santa Cruz do Escalvado");
        this.cidades.add("Santa Efigênia de Minas");
        this.cidades.add("Santa Fé de Minas");
        this.cidades.add("Santa Helena de Minas");
        this.cidades.add("Santa Juliana");
        this.cidades.add("Santa Luzia");
        this.cidades.add("Santa Margarida");
        this.cidades.add("Santa Maria de Itabira");
        this.cidades.add("Santa Maria do Salto");
        this.cidades.add("Santa Maria do Suaçuí");
        this.cidades.add("Santana da Vargem");
        this.cidades.add("Santana de Cataguases");
        this.cidades.add("Santana de Pirapama");
        this.cidades.add("Santana do Deserto");
        this.cidades.add("Santana do Garambéu");
        this.cidades.add("Santana do Jacaré");
        this.cidades.add("Santana do Manhuaçu");
        this.cidades.add("Santana do Paraíso");
        this.cidades.add("Santana do Riacho");
        this.cidades.add("Santana dos Montes");
        this.cidades.add("Santa Rita de Caldas");
        this.cidades.add("Santa Rita de Jacutinga");
        this.cidades.add("Santa Rita de Minas");
        this.cidades.add("Santa Rita de Ibitipoca");
        this.cidades.add("Santa Rita do Itueto");
        this.cidades.add("Santa Rita do Sapucaí");
        this.cidades.add("Santa Rosa da Serra");
        this.cidades.add("Santa Vitória");
        this.cidades.add("Santo Antônio do Amparo");
        this.cidades.add("Santo Antônio do Aventureiro");
        this.cidades.add("Santo Antônio do Grama");
        this.cidades.add("Santo Antônio do Itambé");
        this.cidades.add("Santo Antônio do Jacinto");
        this.cidades.add("Santo Antônio do Monte");
        this.cidades.add("Santo Antônio do Retiro");
        this.cidades.add("Santo Antônio do Rio Abaixo");
        this.cidades.add("Santo Hipólito");
        this.cidades.add("Santos Dumont");
        this.cidades.add("São Bento Abade");
        this.cidades.add("São Brás do Suaçuí");
        this.cidades.add("São Domingos das Dores");
        this.cidades.add("São Domingos do Prata");
        this.cidades.add("São Félix de Minas");
        this.cidades.add("São Francisco");
        this.cidades.add("São Francisco de Paula");
        this.cidades.add("São Francisco de Sales");
        this.cidades.add("São Francisco do Glória");
        this.cidades.add("São Geraldo");
        this.cidades.add("São Geraldo da Piedade");
        this.cidades.add("São Geraldo do Baixio");
        this.cidades.add("São Gonçalo do Abaeté");
        this.cidades.add("São Gonçalo do Pará");
        this.cidades.add("São Gonçalo do Rio Abaixo");
        this.cidades.add("São Gonçalo do Sapucaí");
        this.cidades.add("São Gotardo");
        this.cidades.add("São João Batista do Glória");
        this.cidades.add("São João da Lagoa");
        this.cidades.add("São João da Mata");
        this.cidades.add("São João da Ponte");
        this.cidades.add("São João das Missões");
        this.cidades.add("São João del Rei");
        this.cidades.add("São João do Manhuaçu");
        this.cidades.add("São João do Manteninha");
        this.cidades.add("São João do Oriente");
        this.cidades.add("São João do Pacuí");
        this.cidades.add("São João do Paraíso");
        this.cidades.add("São João Evangelista");
        this.cidades.add("São João Nepomuceno");
        this.cidades.add("São Joaquim de Bicas");
        this.cidades.add("São José da Barra");
        this.cidades.add("São José da Lapa");
        this.cidades.add("São José da Safira");
        this.cidades.add("São José da Varginha");
        this.cidades.add("São José do Alegre");
        this.cidades.add("São José do Divino");
        this.cidades.add("São José do Goiabal");
        this.cidades.add("São José do Jacuri");
        this.cidades.add("São José do Mantimento");
        this.cidades.add("São Lourenço");
        this.cidades.add("São Miguel do Anta");
        this.cidades.add("São Pedro da União");
        this.cidades.add("São Pedro dos Ferros");
        this.cidades.add("São Pedro do Suaçuí");
        this.cidades.add("São Romão");
        this.cidades.add("São Roque de Minas");
        this.cidades.add("São Sebastião da Bela Vista");
        this.cidades.add("São Sebastião da Vargem Alegre");
        this.cidades.add("São Sebastião do Anta");
        this.cidades.add("São Sebastião do Maranhão");
        this.cidades.add("São Sebastião do Oeste");
        this.cidades.add("São Sebastião do Paraíso");
        this.cidades.add("São Sebastião do Rio Preto");
        this.cidades.add("São Sebastião do Rio Verde");
        this.cidades.add("São Tiago");
        this.cidades.add("São Tomás de Aquino");
        this.cidades.add("São Thomé das Letras");
        this.cidades.add("São Vicente de Minas");
        this.cidades.add("Sapucaí-Mirim");
        this.cidades.add("Sardoá");
        this.cidades.add("Sarzedo");
        this.cidades.add("Setubinha");
        this.cidades.add("Sem-Peixe");
        this.cidades.add("Senador Amaral");
        this.cidades.add("Senador Cortes");
        this.cidades.add("Senador Firmino");
        this.cidades.add("Senador José Bento");
        this.cidades.add("Senador Modestino Gonçalves");
        this.cidades.add("Senhora de Oliveira");
        this.cidades.add("Senhora do Porto");
        this.cidades.add("Senhora dos Remédios");
        this.cidades.add("Sericita");
        this.cidades.add("Seritinga");
        this.cidades.add("Serra Azul de Minas");
        this.cidades.add("Serra da Saudade");
        this.cidades.add("Serra dos Aimorés");
        this.cidades.add("Serra do Salitre");
        this.cidades.add("Serrania");
        this.cidades.add("Serranópolis de Minas");
        this.cidades.add("Serranos");
        this.cidades.add("Serro");
        this.cidades.add("Sete Lagoas");
        this.cidades.add("Silveirânia");
        this.cidades.add("Silvianópolis");
        this.cidades.add("Simão Pereira");
        this.cidades.add("Simonésia");
        this.cidades.add("Sobrália");
        this.cidades.add("Soledade de Minas");
        this.cidades.add("Tabuleiro");
        this.cidades.add("Taiobeiras");
        this.cidades.add("Taparuba");
        this.cidades.add("Tapira");
        this.cidades.add("Tapiraí");
        this.cidades.add("Taquaraçu de Minas");
        this.cidades.add("Tarumirim");
        this.cidades.add("Teixeiras");
        this.cidades.add("Teófilo Otoni");
        this.cidades.add("Timóteo");
        this.cidades.add("Tiradentes");
        this.cidades.add("Tiros");
        this.cidades.add("Tocantins");
        this.cidades.add("Tocos do Moji");
        this.cidades.add("Toledo");
        this.cidades.add("Tombos");
        this.cidades.add("Três Corações");
        this.cidades.add("Três Marias");
        this.cidades.add("Três Pontas");
        this.cidades.add("Tumiritinga");
        this.cidades.add("Tupaciguara");
        this.cidades.add("Turmalina");
        this.cidades.add("Turvolândia");
        this.cidades.add("Ubá");
        this.cidades.add("Ubaí");
        this.cidades.add("Ubaporanga");
        this.cidades.add("Uberaba");
        this.cidades.add("Uberlândia");
        this.cidades.add("Umburatiba");
        this.cidades.add("Unaí");
        this.cidades.add("União de Minas");
        this.cidades.add("Uruana de Minas");
        this.cidades.add("Urucânia");
        this.cidades.add("Urucuia");
        this.cidades.add("Vargem Alegre");
        this.cidades.add("Vargem Bonita");
        this.cidades.add("Vargem Grande do Rio Pardo");
        this.cidades.add("Varginha");
        this.cidades.add("Varjão de Minas");
        this.cidades.add("Várzea da Palma");
        this.cidades.add("Varzelândia");
        this.cidades.add("Vazante");
        this.cidades.add("Verdelândia");
        this.cidades.add("Veredinha");
        this.cidades.add("Veríssimo");
        this.cidades.add("Vermelho Novo");
        this.cidades.add("Vespasiano");
        this.cidades.add("Viçosa");
        this.cidades.add("Vieiras");
        this.cidades.add("Mathias Lobato");
        this.cidades.add("Virgem da Lapa");
        this.cidades.add("Virgínia");
        this.cidades.add("Virginópolis");
        this.cidades.add("Virgolândia");
        this.cidades.add("Visconde do Rio Branco");
        this.cidades.add("Volta Grande");
        this.cidades.add("Wenceslau Braz");

        return cidades;
    }
}